### ISSUE TITLE
"BrokenPipeError: [Errno 32] Broken pipe" with the basic examples

### ISSUE THREAD

**Issue by geewrd** [rq/rq#1037]
When running the basic examples I'm having issues with the worker terminating due to a broken pipe error.

This is the worker code I'm running.

```python
from rq import Connection, Worker
def main():
    with Connection():
        w = Worker('default')
        w.work(logging_level='DEBUG')


if __name__ == "__main__":
    main()
```

This is my "long" running task module (my_mod.py).

```python
from time import sleep
def task(p):
    for i in range(1, 10):
        with open('./log', 'a+') as f:
            f.write(f"{i}\n")
            sleep(1)
```

this is where I'm enqueuing the function call

```python
from redis import Redis
from rq import Queue

q = Queue(connection=Redis())

from my_mod import task
job = q.enqueue(task, 'boo')
```

The function completes without issue, but the worker exits with the following exception.

```
$ python3 work.py
22:31:36 Registering birth of worker Elizondo.69458
22:31:36 RQ worker 'rq:worker:Elizondo.69458' started, version 0.13.0
22:31:36 *** Listening on default...
22:31:36 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
22:31:36 Cleaning registries for queue: default
22:31:36 *** Listening on default...
22:31:36 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
22:31:40 default: mod.wr('boo') (2942ee60-8ffc-4ce7-a497-fc3a028f3e53)
22:31:40 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
22:31:40 Sent heartbeat to prevent worker timeout. Next one should arrive within 35 seconds.
22:31:49 default: Job OK (2942ee60-8ffc-4ce7-a497-fc3a028f3e53)
22:31:49 Result is kept for 500 seconds
22:31:49 Registering death
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 599, in send_packed_command
    self._sock.sendall(item)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "work.py", line 11, in <module>
    main()
  File "work.py", line 7, in main
    w.work(logging_level='DEBUG')
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 494, in work
    self.execute_job(job, queue)
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 665, in execute_job
    self.set_state(WorkerStatus.IDLE)
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 331, in set_state
    connection.hset(self.key, 'state', state)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2674, in hset
    return self.execute_command('HSET', name, key, value)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 774, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 612, in send_packed_command
    (errno, errmsg))
redis.exceptions.ConnectionError: Error 32 while writing to socket. Broken pipe.
```

I'm using Redis 5.0.3, and the latest version of rq on Mac OSX High Sierra. 

I've been banging my head against the wall trying to figure this out for a few days now, and I can't find anyone else having this problem, so I assume I'm missing something obvious.

**Comment by scribu** [comment]
I've started experiencing this error when upgrading to RedisPy 3.1. From it's [changelog](https://github.com/andymccurdy/redis-py/blob/master/CHANGES):

> Significant improvements to handing connections with forked processes.

**Comment by scribu** [comment]
I think this is caused by the newest version of [RedisPy](https://github.com/andymccurdy/redis-py/). Temp fix is to pin the version in your requirements file:

```
redis >= 3.0, < 3.1
```

**Comment by geewrd** [comment]
> I think this is caused by the newest version of [RedisPy](https://github.com/andymccurdy/redis-py/), which rq uses under the hood.
> 
> Temp fix is to pin the version in your requirements file:
> 
> ```
> redis >= 3.0, < 3.1
> ```

Yep. this fixes it thanks.

**Comment by mlissner** [comment]
This is affecting Celery too, and I tried the fix in the commit mentioned above, but it doesn't work because it throws a VersionMismatchError from Kombu. I think that means it's still OK for rq folks to use, but this fix won't work for Celery unfortunately.
