### ISSUE TITLE
Tasks keep throwing IOError: [Errno 32] Broken pipe, occasionally works

### ISSUE THREAD

**Issue by kvnramirez** [rq/rq#1070]
Hello, I'm trying to implement a video converter with ffmpeg using redis, rq and django-rq to handle the queue, but sometimes throws this and I don't know what's it's happening 

Traceback (most recent call last):
  File "/home/videoapp/app/env/local/lib/python2.7/site-packages/rq/worker.py", line 799, in perform_job
    rv = job.perform()
  File "/home/videoapp/app/env/local/lib/python2.7/site-packages/rq/job.py", line 600, in perform
    self._result = self._execute()
  File "/home/videoapp/app/env/local/lib/python2.7/site-packages/rq/job.py", line 606, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/videoapp/app/app/cffmpeg/task.py", line 90, in convert_video
    # logger.error('Converting video error', exc_info=True)
  File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    " \"%s\"\n" % self.name)
IOError: [Errno 32] Broken pipe

**Comment by selwin** [comment]
This doesn't look like an error in RQ itself.

**Comment by muralidhar972** [comment]
@selwin please help us with the solution if that is not an error.
