### ISSUE TITLE
Functions with decorators throwing errors

### ISSUE THREAD

**Issue by tonypeng** [rq/rq#1084]
Are decorated functions supported? For example:

job.py
```
def Test(func):
    def _wrapped():
        return func
    return _wrapped

@Test
def some_job():
    pass
```

main.py
```
from redis import Redis
from rq import Queue
import job

q = Queue(connection=Redis())
q.enqueue(job.some_job)
```

This throws an error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rq/job.py", line 199, in func
    return import_attribute(self.func_name)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rq/utils.py", line 156, in import_attribute
    return getattr(module, attribute)
AttributeError: module 'job' has no attribute '_wrapped'
```

**Comment by selwin** [comment]
It seems like your decorator is not returning the correct module path for the decorated function. Try using [functools.wraps](https://docs.python.org/2/library/functools.html#functools.wraps)
