### ISSUE TITLE
ImportError though dependencies are satisfied

### ISSUE THREAD

**Issue by ShubhamRathi** [rq/rq#1091]
I am checking out the use of Redis Queue inside a virtual environment. The directory structure is as follows:

```
Scripts-V3 (Virtualenv is at this level)
├── RQ
│   ├── countwords.py
│   └── queue.py
```

This is the same example as the one given in the [documentation](https://python-rq.org/docs/). 

queue.py is:

```
from rq import Queue
from redis import Redis
from countwords import count_words_at_url
import time

# Tell RQ what Redis connection to use
redis_conn = Redis()
q = Queue(connection=redis_conn)  # no args implies the default queue

# Delay execution of count_words_at_url('http://nvie.com')
job = q.enqueue(count_words_at_url, 'http://nvie.com')
print(job.result)   # => None

# Now, wait a while, until the worker is finished
time.sleep(2)
print(job.result) 
```

I have checked that the required packages (redis, rq) are installed:

```
> pip3 install rq                                                          
Requirement already satisfied: rq in /Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages (1.0)
Requirement already satisfied: redis>=3.0.0 in /Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages (from rq) (3.2.1)
Requirement already satisfied: click>=5.0 in /Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages (from rq) (7.0)
```

Yet, when I run `python3 queue.py`, it fails:
```
Traceback (most recent call last):
  File "queue.py", line 1, in <module>
    from rq import Queue
  File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/rq/__init__.py", line 6, in <module>
    from .connections import (Connection, get_current_connection, pop_connection,
  File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/rq/connections.py", line 7, in <module>
    from redis import Redis
  File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/redis/__init__.py", line 1, in <module>
    from redis.client import Redis, StrictRedis
  File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/redis/client.py", line 10, in <module>
    from redis._compat import (basestring, imap, iteritems, iterkeys,
  File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/redis/_compat.py", line 106, in <module>
    from queue import Queue
  File "/Users/shubhamrathi/Work/driver-pic-orient/Scripts-V3/RQ/queue.py", line 1, in <module>
    from rq import Queue
ImportError: cannot import name 'Queue' from 'rq' (/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/rq/__init__.py)
```

I cant understand why. Whats going on?

**Comment by Hanaasagi** [comment]
See here in your traceback

```
  File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/redis/_compat.py", line 106, in <module>
    from queue import Queue
```

You have a file named `queue.py` in your local directory. It will cause conflict. I think rename `queue.py` to `<file_name>.py` will work.

**Comment by ShubhamRathi** [comment]
> See here in your traceback
> 
> ```
>   File "/Users/shubhamrathi/Work/driver-pic-orient/venv/lib/python3.7/site-packages/redis/_compat.py", line 106, in <module>
>     from queue import Queue
> ```
> 
> You have a file named `queue.py` in your local directory. It will cause conflict. I think rename `queue.py` to `<file_name>.py` will work.

Perfect! Changed the name and it works now :)
