### ISSUE TITLE
Trouble migrating to rq 1.0 // AttributeError: module 'select' has no attribute 'poll'

### ISSUE THREAD

**Issue by meowlz** [rq/rq#1099]
I am trying to migrate to rq 1.0.

However my workers always crash with the following error msg:

I initially thought it is a problem with flask-socketio so please also see here:
https://github.com/miguelgrinberg/Flask-SocketIO/issues/996
```
18:25:28 AttributeError: module 'select' has no attribute 'poll'
Traceback (most recent call last):
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/app/elephant/clientidentification.py", line 18, in clientID_json_generator
    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 400, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/server.py", line 278, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/pubsub_manager.py", line 68, in emit
    'host_id': self.host_id})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/redis_manager.py", line 76, in _publish
    return self.redis.publish(self.channel, pickle.dumps(data))
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 2716, in publish
    return self.execute_command('PUBLISH', channel, message)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 500, in connect
    self._selector = DefaultSelector(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 196, in DefaultSelector
    return _DEFAULT_SELECTOR(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 123, in __init__
    self.read_poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'
Traceback (most recent call last):
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/app/elephant/clientidentification.py", line 18, in clientID_json_generator
    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/flask_socketio/__init__.py", line 400, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/server.py", line 278, in emit
    skip_sid=skip_sid, callback=callback, **kwargs)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/pubsub_manager.py", line 68, in emit
    'host_id': self.host_id})
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/socketio/redis_manager.py", line 76, in _publish
    return self.redis.publish(self.channel, pickle.dumps(data))
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 2716, in publish
    return self.execute_command('PUBLISH', channel, message)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 994, in get_connection
    connection.connect()
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/connection.py", line 500, in connect
    self._selector = DefaultSelector(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 196, in DefaultSelector
    return _DEFAULT_SELECTOR(sock)
  File "/Users/meow/data/phd/phd_projects/pipeline/code/elephant_server/venv/lib/python3.6/site-packages/redis/selector.py", line 123, in __init__
    self.read_poller = select.poll()
AttributeError: module 'select' has no attribute 'poll'
```

I start my workers like this:
```
import os
import redis
from rq import Worker, Queue, Connection

listen = ['heavy', 'default']

redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')

conn = redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```

However I get the same error when spawning workers from terminal. Please help I am out of ideas :(

I use eventlet monkey patching. at the beginning of my code.

**Comment by meowlz** [comment]
So to clarify this...

events.py: ( this emit arrives at the frontend)
```
from .. import socketio, redisqueue
from .clientidentification import clientID_json_generator

@socketio.on('clientidentification')
def schedule_hid_json(hid):
    socketio.emit('status', {'code': 201, 'message': 'clientID json generation queued!'})
    jsongeneration = redisqueue.enqueue(clientID_json_generator, hid, job_timeout=100)
```

clientidentification.py (this emit crashes the worker):
```
from flask_socketio import SocketIO
import json


def clientID_json_generator(hid):
    socketio = SocketIO(message_queue='redis://')
    ...
    unrelated code
    ...

    socketio.emit('status', {'code': 202, 'message': 'client ID json generation finished!'})
```

the worker is started with this script, however a worker started from terminal with "rq worker" crashes with the same error:

```
import os
import redis
from rq import Worker, Queue, Connection

listen = ['heavy', 'default']

redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')

conn = redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```

**Comment by meowlz** [comment]
Okay, I uninstalled everything and reinstalled every dependency. Then updated one app after the other to the most recent version except for scikit-learn checking if it still works after every update...my last steps was to update rq to 1.0 and for some reason it is working now. I did not change any code and I still do not understand what is different now. Maybe it was the update for Flask from 1.0.2 to 1.0.3..I dunno.

if anyone wonders, my working configuration now:

```
eventlet==0.25.0
  - dnspython [required: >=1.15.0, installed: 1.16.0]
  - greenlet [required: >=0.3, installed: 0.4.15]
  - monotonic [required: >=1.4, installed: 1.5]
  - six [required: >=1.10.0, installed: 1.12.0]
Flask-SocketIO==4.0.0
  - Flask [required: >=0.9, installed: 1.0.3]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.15.4]
  - python-socketio [required: >=2.1.0, installed: 4.1.0]
    - python-engineio [required: >=3.8.0, installed: 3.8.0]
      - six [required: >=1.9.0, installed: 1.12.0]
    - six [required: >=1.9.0, installed: 1.12.0]
graphviz==0.11
joblib==0.13.2
matplotlib==3.1.0
  - cycler [required: >=0.10, installed: 0.10.0]
    - six [required: Any, installed: 1.12.0]
  - kiwisolver [required: >=1.0.1, installed: 1.1.0]
    - setuptools [required: Any, installed: 41.0.1]
  - numpy [required: >=1.11, installed: 1.16.4]
  - pyparsing [required: >=2.0.1,!=2.1.6,!=2.1.2,!=2.0.4, installed: 2.4.0]
  - python-dateutil [required: >=2.1, installed: 2.8.0]
    - six [required: >=1.5, installed: 1.12.0]
nilearn==0.5.2
  - nibabel [required: >=2.0.2, installed: 2.4.1]
    - numpy [required: >=1.8, installed: 1.16.4]
    - six [required: >=1.3, installed: 1.12.0]
pipdeptree==0.13.2
  - pip [required: >=6.0.0, installed: 19.1.1]
rq-dashboard==0.5.1
  - arrow [required: Any, installed: 0.14.2]
    - python-dateutil [required: Any, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
  - Flask [required: Any, installed: 1.0.3]
    - click [required: >=5.1, installed: 7.0]
    - itsdangerous [required: >=0.24, installed: 1.1.0]
    - Jinja2 [required: >=2.10, installed: 2.10.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - Werkzeug [required: >=0.14, installed: 0.15.4]
  - redis [required: Any, installed: 3.2.1]
  - rq [required: >=0.3.8, installed: 1.0]
    - click [required: >=5.0, installed: 7.0]
    - redis [required: >=3.0.0, installed: 3.2.1]
sklearn==0.0
  - scikit-learn [required: Any, installed: 0.20.3]
    - numpy [required: >=1.8.2, installed: 1.16.4]
    - scipy [required: >=0.13.3, installed: 1.3.0]
      - numpy [required: >=1.13.3, installed: 1.16.4]
```

**Comment by selwin** [comment]
From the stack trace you provided, the error comes from within your app and not RQ itself. I'm closing this issue.
