### ISSUE TITLE
HorseMonitorTimeoutException: Task exceeded maximum timeout value (30 seconds)

### ISSUE THREAD

**Issue by priyath** [rq/rq#1119]
A bit lost on this one.

I have a queue where I enqueue jobs with a timeout of 172800 seconds (48 hours). Each job performs a long-running data scraping task which can take in excess of 10 hours to complete.

For the most part, this performs as expected. However, I have noticed a sporadic error where some jobs fail with the following (see below) unhandled exception in the logs. 

I also have a custom exception handler added to my worker, but somehow the above error slipped through that as well. It also has a timeout of 30 seconds which I believe is a default value. 

Would appreciate some pointers on possible reasons for this and how I can handle this in the future

Error:
```
2019-07-16 07:45:53,896 - rq.worker - ERROR - Worker f3280d6a6d484727bdcdec2985862caf: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/home/user/project/venv/lib/python3.6/site-packages/rq/worker.py", line 616, in monitor_work_horse
    retpid, ret_val = os.waitpid(self._horse_pid, 0)
  File "/home/user/project/venv/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
rq.timeouts.HorseMonitorTimeoutException: Task exceeded maximum timeout value (30 seconds)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/project/venv/lib/python3.6/site-packages/rq/worker.py", line 477, in work
    self.execute_job(job, queue)
  File "/home/user/project/venv/lib/python3.6/site-packages/rq/worker.py", line 665, in execute_job
    self.monitor_work_horse(job)
  File "/home/user/project/venv/lib/python3.6/site-packages/rq/worker.py", line 621, in monitor_work_horse
    self.heartbeat(self.job_monitoring_interval + 5)
  File "/home/user/project/venv/lib/python3.6/site-packages/rq/worker.py", line 545, in heartbeat
    connection.expire(self.key, timeout)
  File "/home/user/project/venv/lib/python3.6/site-packages/redis/client.py", line 1249, in expire
    return self.execute_command('EXPIRE', name, time)
  File "/home/user/project/venv/lib/python3.6/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/user/project/venv/lib/python3.6/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/user/project/venv/lib/python3.6/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by selwin** [comment]
Reading the logs, I believe RQ freaked out because it's unable to read/write to Redis.

You can ignore `rq.timeouts.HorseMonitorTimeoutException`, because it's just an internal mechanism that RQ uses to periodically send heartbeats to Redis to notify that the job is still running.

![worker py — rq 2019-07-20 17-49-02](https://user-images.githubusercontent.com/188658/61577840-136cb680-ab17-11e9-9efa-9c5c45973ef7.jpg)

**Comment by bt-wil** [comment]
I had a similar error with an emphermal redis connection issue.  The redis cluster failed over to the backup node, and everything was operational within seconds.  However, due to the error, the worker failed, threw an exception, and exited.

Is there a way to avoid exit due to temporary issues?  I'm looking for a way to retry.

I'm using `rq==1.7.0`, similar error logs.

```
08:51:07 Worker rq:worker:28f62ef2c6a14c90b41381c5180432cd: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.6/site-packages/rq/worker.py", line 752, in monitor_work_horse
    retpid, ret_val = self.wait_for_horse()
  File "/path/to/venv/lib/python3.6/site-packages/rq/worker.py", line 420, in wait_for_horse
    pid, stat = os.waitpid(self.horse_pid, 0)
  File "/path/to/venv/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
rq.timeouts.HorseMonitorTimeoutException: Task exceeded maximum timeout value (30 seconds)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.6/site-packages/rq/worker.py", line 579, in work
    self.execute_job(job, queue)
  File "/path/to/venv/lib/python3.6/site-packages/rq/worker.py", line 813, in execute_job
    self.monitor_work_horse(job, queue)
  File "/path/to/venv/lib/python3.6/site-packages/rq/worker.py", line 768, in monitor_work_horse
    pipeline.execute()
  File "/path/to/venv/lib/python3.6/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/path/to/venv/lib/python3.6/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "/path/to/venv/lib/python3.6/site-packages/redis/client.py", line 3978, in parse_response
    self, connection, command_name, **options)
  File "/path/to/venv/lib/python3.6/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/path/to/venv/lib/python3.6/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/path/to/venv/lib/python3.6/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/path/to/venv/lib/python3.6/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/path/to/venv/lib/python3.6/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
08:51:07 Unsubscribing from channel rq:pubsub:28f62ef2c6a14c90b41381c5180432cd
08:51:37 Worker rq:worker:85583cc306a04454800c3ff33962d030: started, version 1.7.0
08:51:37 Subscribing to channel rq:pubsub:85583cc306a04454800c3ff33962d030
```

**Comment by nicbou** [comment]
@selwin, as the person above pointed out, you can't just ignore the issue when it kills your workers.

**Comment by nicbou** [comment]
I had this issue, and a subsequent syntax error killed the workers. The syntax error was caused by an outdated Redis version.
