### ISSUE TITLE
NoSuchJobError when running 'empty' command from rq-dashboard for failed queue

### ISSUE THREAD

**Issue by audiodude** [rq/rq#1132]
When I click on the "empty" button for the failed queue on the rq dashboard, I get the following exception in the rq-dashboard logs:

[2019-08-15 09:41:37,136] ERROR in app: Exception on /queue/failed/empty [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/rq_dashboard/web.py", line 105, in _wrapped
    result_dict = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rq_dashboard/web.py", line 216, in empty_queue
    q.empty()
  File "/usr/local/lib/python3.7/site-packages/rq_dashboard/compat.py", line 57, in empty
    job = Job.fetch(job_id)
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 288, in fetch
    job.refresh()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 461, in refresh
    raise NoSuchJobError('No such job: {0}'.format(self.key))
rq.exceptions.NoSuchJobError: No such job: b'rq:job:7b98b0e6-5760-4ee0-860a-7924c7a66581'

**Comment by selwin** [comment]
`Job.fetch()` raises `NoSuchJobError` if it can't find the corresponding job key in Redis. This is the expected behavior.

You should open an issue in rq-dashboard's repo instead of here.
