### ISSUE TITLE
[Question] not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by rogervila** [rq/rq#1156]
Hello,

I have a wrapper class for RQ that calls the `enqueue` method

```py
class QueueManager(QueueManagerContract):
    def __init__(self):
        self.q = Queue(connection=Redis(host='redis', port=6379, db=0))

    def enqueue(self, method, parameters=None):
        self.q.enqueue(method, parameters)
```

Then, I call the queue like this:

```py
q = QueueManager()
q.enqueue(DummyClass().baz())
```

The queued `baz()` method is executed successfully, which outputs a `test message 2` message.

But then I get this error message:

```
15:09:25 Worker rq:worker:86252ef10f2c4f0b9daa5b8c32f043ac: started, version 1.1.0
15:09:25 *** Listening on default...
15:09:40 default: test message 2() (29c37494-be69-4276-a798-0a51dea48b1e)
15:09:40 ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 200, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python3.7/site-packages/rq/utils.py", line 154, in import_attribute
    module_name, attribute = name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 200, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python3.7/site-packages/rq/utils.py", line 154, in import_attribute
    module_name, attribute = name.rsplit('.', 1)

ValueError: not enough values to unpack (expected 2, got 1)
```

I am relatively new on Python, so maybe there is a noob issue going on here, but I have no idea what it could be.

Thank you.

**Comment by rogervila** [comment]
OK, it looks that is mandatory to pass method parameters, so `parameters` cannot be `None`.

```py
q = QueueManager()
q.enqueue(DummyClass().baz, 'at least one parameter')
```

Question: What if I have a method that does not have parameters?

Thank you,

**Comment by selwin** [comment]
RQ does not support enqueueing instance methods.
