### ISSUE TITLE
Redis data is not unicode compatible (will raise UnicodeDecodeError) if using `Redis(..., decode_responses=True)` instance

### ISSUE THREAD

**Issue by jockerz** [rq/rq#1188]
Hi friends

Here is the code to re-create the exception

```python
# pip install rq redis

from redis import Redis
from rq import Queue

conn = Redis(db=13, password='RedisPassword', decode_responses=True)
conn.flushdb()

queue = Queue(connection=conn)

queue.enqueue(print, 'arg')

job_key = conn.keys('rq:job:*')[0]

# Here come the exception
conn.hgetall(job_key)
```

The exception
```
$ python issue_code.py 
Traceback (most recent call last):
  File "issue_code.py", line 18, in <module>
    conn.hgetall(job_key)
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/client.py", line 2979, in hgetall
    return self.execute_command('HGETALL', name)
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/connection.py", line 356, in read_response
    response = [self.read_response() for i in xrange(length)]
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/connection.py", line 356, in <listcomp>
    response = [self.read_response() for i in xrange(length)]
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/connection.py", line 358, in read_response
    response = self.encoder.decode(response)
  File "/home/hi/rq_issue/venv/lib/python3.7/site-packages/redis/connection.py", line 129, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
```

**Comment by sodrooome** [comment]
as far as i know, you can use `hiredis-py` for handled parsing differently

**Comment by selwin** [comment]
Don't use `decode_responses=True`.

```python
from redis import Redis
from rq import Queue

conn = Redis(db=13)

queue = Queue(connection=conn)

queue.enqueue(print, 'arg')

job_key = conn.keys('rq:job:*')[0]

# Here come the exception
conn.hgetall(job_key)
```

**Comment by aparcar** [comment]
> Don't use decode_responses=True.

Isn't that quite a handy function so you wouldn't have to map over a list to convert from bytes to strings?

**Comment by jockerz** [comment]
I am sorry for late answer.
And thank you guys for answering.

Perhaps the `decode_responses=True` should be on the documentations.
