### ISSUE TITLE
What is the idiomatic way in Python-RQ to handle dependent jobs, when the job they depend on fails?

### ISSUE THREAD

**Issue by MW3000** [rq/rq#1224]
What is the idiomatic way in Python-RQ to handle dependent jobs, when the job they depend on fails?

I work on a media transformation service. I have a download job, on this job depends a transformation job, on this job depends an upload job. If the download job fails for any reason, the depending jobs are obsolete. I can think of the following solutions:

1) Let the download job fail with a Python Exception. Python-RQ will file it as failed and remove the depending jobs.
2) Explicitly remove depending jobs with the job's delete function.
3) Return failure/success information as result of a job and interpret it in the depending jobs.
4) Do not communicate anything between jobs, just let each job check on its own, if its necessary prerequisites are met.

What solution would you choose, and why? Are there other, better solutions?

**Comment by selwin** [comment]
At the moment, if a job fails, we don't do anything with jobs that depends on the successful completion of the first job. In fact, the depending jobs are never enqueued.

I think adding another failure handling mode where a job moves all depending jobs to failed can be considered. But this could be an expensive operation if you have a string of jobs that serially depend on another, like A depends on B that depends on C, etc. When the first job fails, we'll have to move all jobs downstream to the failed queue.

Aside from these two failure modes, I think you'd need to implement your own.

**Comment by MW3000** [comment]
Thank you, @selwin.

**Comment by caffeinatedMike** [comment]
@MW3000 @selwin I'm also looking to accomplish this. Would something like below work as the `on_failure` callback to actually enqueued the dependent jobs?

```python3
from redis import Redis
from rq import Queue

def report_callback(job, connection, *args, **kwargs):
    # success(job, connection, result, *args, **kwargs)
    # failure(job, connection, type, value, traceback)
    redis_conn = Redis()
    # FIXME: How do we make sure job dependency is run,
    #  even when one or more of the jobs fails?
    # TODO: Test the next two lines as a possible solution.
    origin_queue = Queue(name=job.origin, connection=redis_conn)
    origin_queue.enqueue_dependents(job)  # curious if this would be a blocking call?
```

Also, would this call to `enqueue_dependents` be a blocking call in the event there are a handful of jobs that are dependents? I ask because there's a while loop that monitors if all dependencies are met.

**Comment by selwin** [comment]
> Would something like below work as the on_failure callback to actually enqueue the dependent jobs?
Yes, you could use `on_failure` callback to enqueue dependent jobs if you wish to. Having said that, I think it would be better to have a job dependency mechanism that enqueues the dependent jobs regardless of whether the parent job succeeds.

> Also, would this call to enqueue_dependents be a blocking call in the event there are a handful of jobs that are dependents? I ask because there's a while loop that monitors if all dependencies are met.
Well, Redis is inherently single threaded so it can only process one instruction at a time. You do need to be wary of race conditions though.

**Comment by caffeinatedMike** [comment]
> Yes, you could use on_failure callback to enqueue dependent jobs if you wish to. Having said that, I think it would be better to have a job dependency mechanism that enqueues the dependent jobs regardless of whether the parent job succeeds.

That's good to know and I agree with adding functionality for enqueueing dependents regardless of outcome.

> Well, Redis is inherently single threaded so it can only process one instruction at a time. You do need to be wary of race conditions though.

I was more concerned about if the call would block the `rq worker`, not redis itself.

**Comment by caffeinatedMike** [comment]
> Yes, you could use on_failure callback to enqueue dependent jobs if you wish to. Having said that, I think it would be better to have a job dependency mechanism that enqueues the dependent jobs regardless of whether the parent job succeeds.

@selwin I was actually just able to test this out and it unfortunately doesn't work. See below code:
```python3
import time
from rq import Queue

from app.compat import SimpleWindowsWorker  # threading.Timer implementation, see PR #1629


def sleep(seconds=5):
    x = 0
    while x < seconds:
        time.sleep(1)
        x += 1
        print(seconds - x)
        if x == seconds:
            raise ValueError("Umm")
    return None

def failure_callback(job, connection, *args, **kwargs):
    print(f"callback called for {job.id}")
    if job.dependent_ids:
        print(f"enqueueing dependents in {job.origin}")  # this gets printed, but dependent is never actually queued
        origin_queue = Queue(name=job.origin, connection=connection)
        origin_queue.enqueue_dependents(job)

def final_callback(job, connection, *args, **kwargs):
    print("final_callback called")  # never printed

def test():
    # test if the q.enqueue_dependents(job) will block the rq-worker until all related tasks
    # from which the final task is dependent upon have complete/failed if called inside on_failure callback

    q = Queue(connection=Redis.from_url("redis://"))
    q.empty()
    job_1 = q.enqueue("app.sleep", on_failure=failure_callback)
    job_2 = q.enqueue("app.sleep", on_failure=failure_callback)
    job_3 = q.enqueue("app.sleep", on_failure=failure_callback)
    last_job = q.enqueue(
        "app.sleep",
        on_success=final_callback,
        on_failure=final_callback,
        depends_on=[job_1, job_2, job_3]
    )

    w = SimpleWindowsWorker([q], connection=q.connection)
    w.work(burst=True)
    # last_job never gets called :(
```

Resulting logs:
```
(linux-venv) ubuntu@MICHAELH-ZB:/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal$ python
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from app import test
>>> test()
13:21:03 Worker rq:worker:19913f326e5c47d6b31a729b94a86c56: started, version 1.10.1
13:21:03 Subscribing to channel rq:pubsub:19913f326e5c47d6b31a729b94a86c56
13:21:03 *** Listening on default...
13:21:03 default: app.sleep() (3bf7c7c3-811d-47de-90ea-49809f52a478)
4
3
2
1
0
callback called for 3bf7c7c3-811d-47de-90ea-49809f52a478
enqueueing dependents in default
13:21:08 Traceback (most recent call last):
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal/app/__init__.py", line 131, in sleep
    raise ValueError("Umm")
ValueError: Umm
Traceback (most recent call last):
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal/app/__init__.py", line 131, in sleep
    raise ValueError("Umm")
ValueError: Umm
13:21:08 default: app.sleep() (83a2a7e2-0cee-4ca0-ac5c-fe0d647364e6)
4
3
2
1
0
callback called for 83a2a7e2-0cee-4ca0-ac5c-fe0d647364e6
enqueueing dependents in default
13:21:13 Traceback (most recent call last):
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal/app/__init__.py", line 131, in sleep
    raise ValueError("Umm")
ValueError: Umm
Traceback (most recent call last):
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal/app/__init__.py", line 131, in sleep
    raise ValueError("Umm")
ValueError: Umm
13:21:13 default: app.sleep() (ebbfda2e-a8a7-413c-afe6-e01a500743c9)
4
3
2
1
0
callback called for ebbfda2e-a8a7-413c-afe6-e01a500743c9
enqueueing dependents in default
13:21:18 Traceback (most recent call last):
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal/app/__init__.py", line 131, in sleep
    raise ValueError("Umm")
ValueError: Umm
Traceback (most recent call last):
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/ubuntu/linux-venv/lib/python3.6/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/mnt/c/users/mhill/pycharmprojects/daap_reporting_portal/app/__init__.py", line 131, in sleep
    raise ValueError("Umm")
ValueError: Umm
13:21:18 Worker rq:worker:19913f326e5c47d6b31a729b94a86c56: done, quitting
13:21:18 Unsubscribing from channel rq:pubsub:19913f326e5c47d6b31a729b94a86c56
```

Any idea on how I can accomplish this currently?

**Comment by selwin** [comment]
@caffeinatedMike that's because `queue.enqueue_dependents()` checks whether or not each job's [dependencies are met](https://github.com/rq/rq/blob/7be119068f31db165f8f3fea48d34a00ab587c02/rq/queue.py#L632) before enqueueing them. Remember that one job can have multiple dependencies.

What we can do is add a `check_dependencies` flag to this method. If set to `False`, we can skip the dependencies check and enqueue all the dependents.

**Comment by caffeinatedMike** [comment]
@selwin I'm actually working on tests for the the official support of `Dependency(..., allow_failure=True)` functionality from PR #1611. I'm about to open up a PR that includes updates to that code.

**Comment by selwin** [comment]
> I'm actually working on tests for the the official support of Dependency(..., allow_failure=True) functionality from PR https://github.com/rq/rq/pull/1611. I'm about to open up a PR that includes updates to that code.

Cool, let me know if there's something I can review. While you're at it, can you think of an alternative name for [dependency_allow_fail](https://github.com/rq/rq/pull/1611/files#diff-5ff734c15373fbcdb39d32faf0555265d8eaae657c1a6174e5e9b0dedd2815f7R424)?
