### ISSUE TITLE
Broken Pipe error with multiprocessing

### ISSUE THREAD

**Issue by tactycHQ** [rq/rq#1250]
I keep getting  Broken Pipe error if my job times out before it has finished. In the error log below, the job time out limit is 10 seconds and as soon as that limit is reached, the job stops but this results in the Broken Pipe error

Error log below:
```
worker_1       |   File "/usr/src/server/api/routes.py", line 232, in calculateJob
worker_1       |     solutions, warnings, caches = binary.calculateSolutions(inputs=inputs, outputs=outputs,last_solutions=last_solution['solutions'])
worker_1       |   File "/usr/src/server/calcengine/modelwrapper.py", line 156, in calculateSolutions
worker_1       |     return self.processCalcs(chunks, cache=cache, outputs=outputs)
worker_1       |   File "/usr/src/server/calcengine/modelwrapper.py", line 217, in processCalcs
worker_1       |     computedResults = pool.map(partial_func, chunks)
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 364, in map
worker_1       |     return self._map_async(func, iterable, mapstar, chunksize).get()
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 762, in get
worker_1       |     self.wait(timeout)
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 759, in wait
worker_1       |     self._event.wait(timeout)
worker_1       |   File "/usr/local/lib/python3.8/threading.py", line 558, in wait
worker_1       |     signaled = self._cond.wait(timeout)
worker_1       |   File "/usr/local/lib/python3.8/threading.py", line 302, in wait
worker_1       |     waiter.acquire()
worker_1       |   File "/usr/local/lib/python3.8/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
worker_1       |     raise self._exception('Task exceeded maximum timeout value '
**worker_1       | rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (10** seconds)
worker_1       | INFO:rq.worker:calculate: Job OK (e9363705-0595-4174-8195-de443094e8c6)
worker_1       | INFO:rq.worker:Result is kept for 500 seconds
worker_1       | Process ForkPoolWorker-1:
worker_1       | Traceback (most recent call last):
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 131, in worker
worker_1       |     put((job, i, result))
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 368, in put
worker_1       |     self._writer.send_bytes(obj)
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
worker_1       |     self._send_bytes(m[offset:offset + size])
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
worker_1       |     self._send(header)
worker_1       |   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 368, in _send
worker_1       |     n = write(self._handle, buf)
**worker_1       | BrokenPipeError: [Errno 32] Broken pipe**
```

It may be important to know that the worker itself is using python
s multiprocessing module as such:

```
pool = mp.Pool()
computedResults = pool.map(partial_func, chunks)

```

I suspect this may be as processes are still ongoing at the time the TimeOutException is caught.

**Comment by lowercase00** [comment]
Closing in favor of #1790
