### ISSUE TITLE
Trying to parse empty string as date time

### ISSUE THREAD

**Issue by im-n1** [rq/rq#1282]
I tried to use these apps:

* https://github.com/Parallels/rq-dashboard
* https://github.com/pranavgupta1234/rqmonitor

Both of these apps raise an exception inside rq library when trying to ask to jobs status.
Here is the traceback:

```
dashboard_1  | 09:17:55: Exception on /0/data/jobs/default/started/8/1.json [GET]
dashboard_1  | Traceback (most recent call last):
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/utils.py", line 169, in utcparse
dashboard_1  |     return datetime.datetime.strptime(string, _TIMESTAMP_FORMAT)
dashboard_1  |   File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
dashboard_1  |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
dashboard_1  |   File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
dashboard_1  |     (data_string, format))
dashboard_1  | ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
dashboard_1  |
dashboard_1  | During handling of the above exception, another exception occurred:
dashboard_1  |
dashboard_1  | Traceback (most recent call last):
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
dashboard_1  |     response = self.full_dispatch_request()
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
dashboard_1  |     rv = self.handle_user_exception(e)
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
dashboard_1  |     reraise(exc_type, exc_value, tb)
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
dashboard_1  |     raise value
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
dashboard_1  |     rv = self.dispatch_request()
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
dashboard_1  |     return self.view_functions[rule.endpoint](**req.view_args)
dashboard_1  |   File "/rq_dashboard/web.py", line 101, in _wrapped
dashboard_1  |     result_dict = f(*args, **kwargs)
dashboard_1  |   File "/rq_dashboard/web.py", line 428, in list_jobs
dashboard_1  |     queue_name, registry_name, offset, per_page
dashboard_1  |   File "/rq_dashboard/web.py", line 233, in get_queue_registry_jobs_count
dashboard_1  |     current_queue_jobs = [queue.fetch_job(job_id) for job_id in job_ids]
dashboard_1  |   File "/rq_dashboard/web.py", line 233, in <listcomp>
dashboard_1  |     current_queue_jobs = [queue.fetch_job(job_id) for job_id in job_ids]
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/queue.py", line 147, in fetch_job
dashboard_1  |     job = self.job_class.fetch(job_id, connection=self.connection)
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 299, in fetch
dashboard_1  |     job.refresh()
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 506, in refresh
dashboard_1  |     self.restore(data)
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 475, in restore
dashboard_1  |     self.ended_at = str_to_date(obj.get('ended_at'))
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/utils.py", line 256, in str_to_date
dashboard_1  |     return utcparse(as_text(date_str))
dashboard_1  |   File "/usr/local/lib/python3.7/site-packages/rq/utils.py", line 172, in utcparse
dashboard_1  |     return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%SZ')
dashboard_1  |   File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
dashboard_1  |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
dashboard_1  |   File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
dashboard_1  |     (data_string, format))
dashboard_1  | ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by pranavgupta1234** [comment]
Hi @im-n1 

This might be related to https://github.com/rq/rq/issues/1225 but I tested with creating jobs that timeout and rqmonitor was able to render without the above error.
Please let me your setup so I can reproduce this error. Also, which version of rq are you using ?

**Comment by im-n1** [comment]
Sorry I don't have the code available anymore. But it was pretty much basic set.

I used latest version of rq.

**Comment by pranavgupta1234** [comment]
Were the jobs timed out ?

**Comment by kjhenner** [comment]
I'm having the same problem.
rq.utils.str_to_date(date_string) returns None if date_string evaluates as false (which the empty string will), so it's strange that the empty string is getting through to the utcparse function to cause that error. The actual setup I'm using is in a private repo, so I'll see if I can come up with a minimal example to reproduce the issue.
I'm using the eoranged/rq-dashboard:latest image (build from https://github.com/Parallels/rq-dashboard/tree/318771473cb4ccc9bc6faa31607eef741561fc27)

**Comment by selwin** [comment]
This should already be fixed in https://github.com/rq/rq/commit/cfe389bd65769ef1db7c01dbda11a6ba61e621c4
