### ISSUE TITLE
Redis version check fails for four-digit version numbers, such as 3.0.7.9

### ISSUE THREAD

**Issue by stephankoe** [rq/rq#1317]
When connecting RQ 1.5.0 to Redis 3.0.7.9, I get the following error after starting `rq`:

```
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rq/cli/cli.py", line 78, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rq/cli/cli.py", line 268, in worker
    max_jobs=max_jobs, with_scheduler=with_scheduler)
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 511, in work
    self.register_birth()
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 295, in register_birth
    if self.get_redis_server_version() >= StrictVersion("4.0.0"):
  File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 227, in get_redis_server_version
    self.connection.info("server")["redis_version"]
  File "/usr/local/lib/python3.6/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/local/lib/python3.6/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '3.0.7.9'
```

Apparently, this is due to a recently added chunk of code in `worker.py:register_birth()`, where the version number is checked. Python's library code seems to have problems with such version numbers. Therefore, the latest RQ is incompatible with all four-digit Redis versions.

**Comment by selwin** [comment]
I'll try to release a patch sometime in the next few days.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1322
