### ISSUE TITLE
Is it possible to pass in Werkzeug FileStorage types?

### ISSUE THREAD

**Issue by Jont828** [rq/rq#1321]
I'm working on a Flask app where users upload image files. Those files get passed to a function to be processed in a background task where the function looks something like this:
```
def process_file(files=[]):
...
q.enqueue_call(func=detect, args=(name, email, file))
```
When I try to do that, I'm getting an issue where it leads to a recursion depth error.
```
00:12:42 Worker rq:worker:951c7280d0e743179da7f19e2fe2c3d4: started, version 1.5.0
00:12:42 *** Listening on default...
00:12:48 default: app.detect('username, 'email', [<FileStorage: 'image-1.jpg' ('image/jpeg')>]) (6efa8706-428a-4a8c-8122-e9dfb30cc1e7)
00:12:48 Worker rq:worker:951c7280d0e743179da7f19e2fe2c3d4: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/worker.py", line 552, in work
    self.execute_job(job, queue)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/worker.py", line 775, in execute_job
    self.fork_work_horse(job, queue)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/worker.py", line 705, in fork_work_horse
    self.main_work_horse(job, queue)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/worker.py", line 788, in main_work_horse
    self.perform_job(job, queue)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/worker.py", line 925, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/worker.py", line 828, in prepare_job_execution
    self.procline(msg.format(job.func_name, job.origin, time.time()))
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/job.py", line 246, in func_name
    self._deserialize_data()
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/rq/job.py", line 214, in _deserialize_data
    self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/werkzeug/datastructures.py", line 3089, in __getattr__
    return getattr(self.stream, name)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/werkzeug/datastructures.py", line 3089, in __getattr__
    return getattr(self.stream, name)
  File "/Users/jtong/.local/share/virtualenvs/Flask-App-zsnJIj1w/lib/python3.8/site-packages/werkzeug/datastructures.py", line 3089, in __getattr__
    return getattr(self.stream, name)
  [Previous line repeated 987 more times]
RecursionError: maximum recursion depth exceeded
```

However, I noticed that when I read the image out as a stream of bytes `(files_bytes = [files.read() for file in files],` it worked and I didn't have an issue with enqueue anymore. I'm not sure if passing in file data is something a user is supposed to be able to do (perhaps it would be better to just use a db instead), but I'm a little confused as to why passing in a stream of bytes works but not the FileStorage type.

**Comment by yomajo** [comment]
Similar, but not exact. Expected to be able to save inside job, but best I could do is save on route and pass path to job function.

On route I have
```
    all_files = request.files.getlist('order_files')
    q = Queue(name='default')
    job_ids = []

    for file_storage in all_files:
        job = Job.create(func=deal_with_upload, args=(file_storage,), description='order_file_processing')
        q.enqueue_job(job)

        job_ids.append(job.id)
```

End of exception:
```
File "/<my_cute_filesystem>/.venv/lib/python3.10/site-packages/rq/job.py", line 285, in _deserialize_data
    raise DeserializationError() from e
rq.exceptions.DeserializationError

``` 
This fails to deserialize, so I'm assuming rq does not allow FileStorage object as function argument.

**Comment by yomajo** [comment]
At this problem again, only this time I don't need uploaded files in backend (only for processing, not storing).

Inspired by @s-junio , found this works fine:
```
import tempfile
[...]
        all_files_raw = request.files.getlist('order_files')
        all_files: list[tempfile.SpooledTemporaryFile] = [f.stream for f in all_files_raw]

        job = Job.create(
            func=processing_func,
            args=(all_files,),
            id='custom_id_123',
            connection=redis_conn)
        q.enqueue_job(job)
[...]
```
