### ISSUE TITLE
Click 8.0.0 breaks workers in Python 3.8

### ISSUE THREAD

**Issue by davidhariri** [rq/rq#1469]
Suggest we pin `click==7.1.2` in requirements.txt to avoid this bug in the future

Error:
```
Traceback (most recent call last):
  File "/Users/ada/.pyenv/versions/article-service/bin/rq", line 6, in <module>
    from rq.cli import main
  File "/Users/ada/.pyenv/versions/3.8.0/envs/article-service/lib/python3.8/site-packages/rq/cli/__init__.py", line 2, in <module>
    from .cli import main
  File "/Users/ada/.pyenv/versions/3.8.0/envs/article-service/lib/python3.8/site-packages/rq/cli/cli.py", line 99, in <module>
    def empty(cli_config, all, queues, **options):
  File "/Users/ada/.pyenv/versions/3.8.0/envs/article-service/lib/python3.8/site-packages/rq/cli/cli.py", line 77, in pass_cli_config
    func = option(func)
  File "/Users/ada/.pyenv/versions/3.8.0/envs/article-service/lib/python3.8/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/ada/.pyenv/versions/3.8.0/envs/article-service/lib/python3.8/site-packages/click/core.py", line 2467, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/Users/ada/.pyenv/versions/3.8.0/envs/article-service/lib/python3.8/site-packages/click/core.py", line 2106, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.
```

**Comment by rpkak** [comment]
This should be fixed in rq version 1.8.1. View #1464 #1465.

**Comment by rpkak** [comment]
Can this issue be closed?

**Comment by carlosribas** [comment]
I keep getting the exact same error even using rq in version 1.8.1. Has this problem really been fixed?

**Comment by rpkak** [comment]
Should be fixed. Make sure you have run `pip install -r requirements.txt` after updating `requirements.txt`. Otherwise please paste your exact error logs.

**Comment by carlosribas** [comment]
Ops, my bad. The error is exactly the same, but in my case it happens because of the rq-dashboard package. Sorry to bother you with that.

**Comment by moi90** [comment]
Could you create a post-release for 1.4.3 which includes `click<8.0.0` or something?

**Comment by rpkak** [comment]
> Could you create a post-release for 1.4.3 which includes `click<8.0.0` or something?

@moi90 you could test c5fa8b17f9cbfb10d570c5b501c9d968f4948754?

@selwin you could create a release from it.

**Comment by selwin** [comment]
@moi90 this has been fixed in RQ’s latest release. If you’re using an older version of RQ, you should pin your click dependency in your project.

Unfortunately we don’t have the bandwidth to support old releases.

**Comment by moi90** [comment]
> Unfortunately we don’t have the bandwidth to support old releases.

Alright, I understand that!

(The reason I ask is: In my environment, conda prefers an older version of rq for some reason. If this older version would contain the information that it needs Click < 8.0.0, then conda could fix the problem itself.)
