### ISSUE TITLE
Unhandled intermittent redis failures

### ISSUE THREAD

**Issue by waldner** [rq/rq#1478]
Once in a while I get exceptions in the logs like the following:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
    for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rq/worker.py", line 1003, in perform_job
    self.prepare_job_execution(job, heartbeat_ttl)
  File "/app/app_utils.py", line 125, in prepare_job_execution
    super().prepare_job_execution(job, heartbeat_ttl)
  File "/usr/lib/python3.8/site-packages/rq/worker.py", line 890, in prepare_job_execution
    pipeline.execute()
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to redis.internal:6379. Try again.
```

(Ok this one I could catch since it actually comes from a call in my code, but there are other instances where I don't have any control over it).

I know for a fact that these errors are transient, as I can immediately requeue the job and it works without problems.
Would it be possible to either handle these errors from rq itself (eg retry a configurable number of times), or expose the error to user code and give users the option to handle them themselves?

**Comment by selwin** [comment]
RQ version >= 1.8.0 tries to reconnect to Redis whenever if loses Redis connection. This is the [related pull request](https://github.com/rq/rq/pull/1387). Does this help?

**Comment by waldner** [comment]
I do have 1.8.0. Here's another one I just spotted (this is entirely internal to RQ, no code of mine involved):

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 584, in _connect
    for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/rq/worker.py", line 1015, in perform_job
    self.handle_job_success(job=job,
  File "/usr/lib/python3.8/site-packages/rq/worker.py", line 985, in handle_job_success
    job.cleanup(result_ttl, pipeline=pipeline,
  File "/usr/lib/python3.8/site-packages/rq/job.py", line 777, in cleanup
    self.delete(pipeline=pipeline, remove_from_queue=remove_from_queue)
  File "/usr/lib/python3.8/site-packages/rq/job.py", line 651, in delete
    if self.is_finished:
  File "/usr/lib/python3.8/site-packages/rq/job.py", line 157, in is_finished
    return self.get_status() == JobStatus.FINISHED
  File "/usr/lib/python3.8/site-packages/rq/job.py", line 146, in get_status
    self._status = as_text(self.connection.hget(self.key, 'status'))
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 3010, in hget
    return self.execute_command('HGET', name, key)
  File "/usr/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to redis.sunreport.internal:6379. Try again.
```

**Comment by Asrst** [comment]
The above ones are some interesting cases, where connection is lost while job is till being executed/ or in process. Because rq cannot connect to redis, it wont be able to update the Status of the job as well.  While the previous pull request helps to re-establish the connection to redis, the above job status will remain in `STARTED` state forever. This may be also reason for loss of few jobs reported in other issues.

I build a wrapper around the `Redis` to wait & retry in case execution of commands fails. But, I feel this is more of redis-py issue, If `Redis` can natively offer an option to wait/retry incase connection fails.

By retrying/waiting at Redis command, the `Worker` will stop at that failure point , till the redis connection is back.
@selwin , Would love to hear your thoughts as well, if there are better ways to deal with this issue.


```python

from redis import Redis
from functools import wraps
import time

def retry(retries=5, delay=10, max_backoff=60):
    def retry_with_backoff(f):
        @wraps(f)
        def f_retry(*args, **kwargs):
            arg_dict = {'retries': retries,
                        'delay': delay, 
                        'max_backoff': max_backoff}
            num_retries = 0
            while arg_dict['retries'] > 1:
                try:
                    return f(*args, **kwargs)
                except Exception as e:
                    exp_backoff = arg_dict['delay'] * (2 ** num_retries)
                    sleep_delay = min(exp_backoff, arg_dict['max_backoff'])
                    msg = "Exception:{},Retrying in {} sec...".format(e, sleep_delay)
                    print(msg)
                    time.sleep(sleep_delay)
                    arg_dict['retries'] -= 1
                    num_retries += 1
            return f(*args, **kwargs)
        return f_retry
    return retry_with_backoff

class RedisRetry(Redis):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    @retry(5, 10)
    def execute_command(self,*args, **options):
        return super().execute_command(*args, **options)
    
    
rc = RedisRetry()
print('Set value in Redis:', rc.hset("NumberToString", "5", "Five"))
print('Retriving value:', rc.hget("NumberToString", "5"))
all_keys = list(rc.hgetall('NumberToString').keys())
print('Deleting ALL Keys:', rc.hdel('NumberToString', *all_keys))

```

**Comment by waldner** [comment]
I don't know if it's related, but this improved a lot with 1.10. I haven't seen any of these errors since I upgraded to 1.10. Leaving open for a few days more, if the problem does not happen again I'll close the bug.
