### ISSUE TITLE
Exception during worker setup leaves pubsub thread running, app doesn't exit

### ISSUE THREAD

**Issue by dang-cb** [rq/rq#1496]
When running `Worker.work()` during the startup it creates a pubsub subscription thread, and then hits Redis to `set_state(WorkerStatus.STARTED)`.

If a Redis exception is raised in `set_state` (in my case, a `SERVER_CLOSED_CONNECTION_ERROR`) the main thread exits, but the pubsub thread is left running as it is never unsubscribed.

As I'm running this worker on Heroku, the app therefore doesn't exit, and Heroku's dyno monitor doesn't restart it. The worker is in limbo until it is manually restarted.

As Heroku cycles all dynos daily, I'm experiencing this 2-3 times a week, as there seems to be something in my environment that makes a server disconnect quite likely during worker startup! (Something I'm investigating separately).

Full stack trace:
```
2021-06-17T19:52:34.318132+00:00 host app worker.1 - Starting worker...
2021-06-17T19:57:27.176765+00:00 host app worker.1 - Traceback (most recent call last):
2021-06-17T19:57:27.176812+00:00 host app worker.1 -   File "manage.py", line 40, in <module>
2021-06-17T19:57:27.177201+00:00 host app worker.1 -     cli()
2021-06-17T19:57:27.177204+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-06-17T19:57:27.17796+00:00 host app worker.1 -     return self.main(*args, **kwargs)
2021-06-17T19:57:27.177965+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-06-17T19:57:27.178437+00:00 host app worker.1 -     rv = self.invoke(ctx)
2021-06-17T19:57:27.178475+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-06-17T19:57:27.179136+00:00 host app worker.1 -     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-06-17T19:57:27.17914+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-06-17T19:57:27.182369+00:00 host app worker.1 -     return ctx.invoke(self.callback, **ctx.params)
2021-06-17T19:57:27.18237+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-06-17T19:57:27.182705+00:00 host app worker.1 -     return callback(*args, **kwargs)
2021-06-17T19:57:27.182709+00:00 host app worker.1 -   File "manage.py", line 29, in worker
2021-06-17T19:57:27.182842+00:00 host app worker.1 -     workers.worker.start()
2021-06-17T19:57:27.182846+00:00 host app worker.1 -   File "/app/workers/worker.py", line 22, in start
2021-06-17T19:57:27.182972+00:00 host app worker.1 -     worker.work(logging_level="WARNING")
2021-06-17T19:57:27.182976+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/rq/worker.py", line 548, in work
2021-06-17T19:57:27.183281+00:00 host app worker.1 -     self.set_state(WorkerStatus.STARTED)
2021-06-17T19:57:27.183282+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/rq/worker.py", line 356, in set_state
2021-06-17T19:57:27.185047+00:00 host app worker.1 -     connection.hset(self.key, 'state', state)
2021-06-17T19:57:27.185048+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 3050, in hset
2021-06-17T19:57:27.185048+00:00 host app worker.1 -     return self.execute_command('HSET', name, *items)
2021-06-17T19:57:27.185051+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
2021-06-17T19:57:27.185428+00:00 host app worker.1 -     return self.parse_response(conn, command_name, **options)
2021-06-17T19:57:27.185457+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
2021-06-17T19:57:27.18595+00:00 host app worker.1 -     response = connection.read_response()
2021-06-17T19:57:27.18598+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
2021-06-17T19:57:27.186435+00:00 host app worker.1 -     response = self._parser.read_response()
2021-06-17T19:57:27.186471+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
2021-06-17T19:57:27.186754+00:00 host app worker.1 -     raw = self._buffer.readline()
2021-06-17T19:57:27.186778+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
2021-06-17T19:57:27.187046+00:00 host app worker.1 -     self._read_from_socket()
2021-06-17T19:57:27.187075+00:00 host app worker.1 -   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
2021-06-17T19:57:27.187291+00:00 host app worker.1 -     raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
2021-06-17T19:57:27.187352+00:00 host app worker.1 - redis.exceptions.ConnectionError: Connection closed by server.
```
(It's always 5 minutes after worker start)

The workaround I'm using to force the worker to unsubscribe on exception is:
```
with Connection(conn):
    worker = HerokuWorker(map(Queue, listen))
    try:
        worker.work(logging_level="INFO")
    except:
        worker.unsubscribe()
```

**Comment by selwin** [comment]
I think moving [self.subscribe()](https://github.com/rq/rq/blob/master/rq/worker.py#L564) into the beginning of [try/except block here](https://github.com/rq/rq/blob/master/rq/worker.py#L586) should solve the issue.

**Comment by mik3y** [comment]
Hi @dang-cb,

> As Heroku cycles all dynos daily, I'm experiencing this 2-3 times a week, as there seems to be something in my environment that makes a server disconnect quite likely during worker startup! (Something I'm investigating separately).

Are you by chance using Redis from Redis Labs? We've experienced something similar, and I believe they have a rootcause on their end which is yet to be deployed. I haven't received complete confirmation from them yet, but what they have said is an "unexpected" client behavior (specifically, unsubscribe on a non-subscribed channel) causes their server to treat the connection as stale and disconnect others.

In any event, the syndrome for us with heroku & rq is the same as your original report here: RQ workers often hang when we re-deploy. Thanks for sharing your workaround.

**Comment by mik3y** [comment]
Hi @selwin,

> I think moving self.subscribe() into the beginning of try/except block here should solve the issue.

Looks right to me too (although I'm much less familiar with the rq codebase than you).

One other option that struck my eye: The pubsub thread could be [run in daemon mode](https://docs.python.org/3/library/threading.html#thread-objects). I think this would prevent a worker process from hanging around when the main thread has crashed but the pubsub thread has not.

It looks like redis-py does support a [`daemon=True|False` kwarg to `run_in_thread`](https://github.com/andymccurdy/redis-py/blob/3.5.3/redis/client.py#L3688). I'm not sure if there might be other, unwanted side-effects from changing pubsub thread behavior this way. What do you think?

I'd be happy to prepare a PR for either/both pending your feedback

**Comment by selwin** [comment]
If running the thread in daemon mode solves the issue, I'd be happy to accept a PR for that. Letting the library do the work for us is safer than moving things around.

**Comment by mik3y** [comment]
> If running the thread in daemon mode solves the issue, I'd be happy to accept a PR for that. Letting the library do the work for us is safer than moving things around.

Yes, I think that will solve the original issue - a functionally dead, but non-terminating, worker process. I will prepare the PR (and see if there's any low-impact way to unittest).

Responding to my earlier question on side-effects: From what I can tell about the `work()` method, it isn't expected nor intended that any work continues after the method returns. So I am doubtful there are valid uses out there that depend on the robust, non-daemonic behavior of this thread, and the change should be safe.

**Comment by dang-cb** [comment]
> Are you by chance using Redis from Redis Labs? We've experienced something similar, and I believe they have a rootcause on their end which is yet to be deployed. I haven't received complete confirmation from them yet, but what they have said is an "unexpected" client behavior (specifically, unsubscribe on a non-subscribed channel) causes their server to treat the connection as stale and disconnect others.

Yes, it was with Redis Labs - I've not experienced the same with Heroku's own Redis servers, and originally suspected it was to do with networking over boundaries / firewalling etc.
Interesting to read about "unexpected client behaviour" potentially causing this - sounds likely with my code :wink:
