### ISSUE TITLE
raspberry pi fails to run task because of pickle protocol version 5?

### ISSUE THREAD

**Issue by vfxdee** [rq/rq#1505]
I have pickle 5 on my system and have confirmed that it's installed.  I can import it just fine, but any time I submit a job to redisQueue and it picks up on my raspberry pi, I get this error:

>>> print(job.exc_info)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/rq/worker.py", line 1008, in perform_job
    self.prepare_job_execution(job)
  File "/home/pi/.local/lib/python3.7/site-packages/rq/worker.py", line 905, in prepare_job_execution
    self.procline(msg.format(job.func_name, job.origin, time.time()))
  File "/home/pi/.local/lib/python3.7/site-packages/rq/job.py", line 256, in func_name
    self._deserialize_data()
  File "/home/pi/.local/lib/python3.7/site-packages/rq/job.py", line 224, in _deserialize_data
    self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data)
ValueError: unsupported pickle protocol: 5

I just am testing right now with a simple add method giving me a sum of a list of numbers as a test for the queue. 
12:40:37 piQueue: myQueue.add([6, 4, 8, 2]) (5751938d-3123-4c5e-8180-43cffb8d449a)

 It fails on anything I try to do with this same error.  I've tried changing the serializer to None, also to JSON and it never has any effect on the error.  Even with None or JSON it says the pickle protocol is unsupported.  Does anyone know what I need to do?
$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle5
>>> 

pickle imports fine and the error persists, so is this a bug somewhere or do I have a setting wrong?

My submission goes like:
from myQueue import add
from time import sleep
redis_conn = Redis(server, 6380, password=pass)
q = Queue('piQueue',connection=redis_conn, serializer=None)
job = q.enqueue(add, [6,4,8,2])
print(job.result)
sleep(5)
job.refresh()
print(job.result)
print(job.exc_info)

Which returns the error above.

**Comment by vfxdee** [comment]
Nevermind.  Answered my own question.  I didn't see that pi has python 3.7 installed, not 3.8.
