### ISSUE TITLE
Google Memory Store Redis doesn't allow CLIENT commands

### ISSUE THREAD

**Issue by sbv-csis** [rq/rq#1508]
CLIENT command is disabled for Google memory store: https://cloud.google.com/memorystore/docs/redis/product-constraints

Which means version 1.9.0 doesn't work on google memory store (Due to [PR 1463](https://github.com/rq/rq/pull/1463/files#diff-50984f276e8a6fea5f4ba4938afb6f4fbc544fd3751fbd16027dc0a326d6405eR224))
```
Traceback (most recent call last):
  File "/venv/bin/rq", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/rq/cli/cli.py", line 83, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/rq/cli/cli.py", line 248, in worker
    worker = cli_config.worker_class(
  File "/venv/lib/python3.9/site-packages/rq/worker.py", line 224, in __init__
    connection.client_setname(self.name)
  File "/venv/lib/python3.9/site-packages/redis/client.py", line 1206, in client_setname
    return self.execute_command('CLIENT SETNAME', name)
  File "/venv/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/venv/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `CLIENT`, with args beginning with: `SETNAME`, `7120f0794a7441cbb6e85cdfa5bfc736`, 
```
redis `INFO` output on Google Memory Store

``` 
# Server
redis_version:5.0.9
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:a7a22e23ea48819b
redis_mode:standalone
os:Linux 4.19.112+ x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
process_id:1
run_id:f6cd9f97502b60169cc49e749ee55126a2b04b0d
tcp_port:6379
uptime_in_seconds:346008
uptime_in_days:4
hz:10
configured_hz:10
lru_clock:14870793
executable:/data/redis-server
config_file:/usr/local/etc/redis/redis.conf

....
```

**Comment by cesarferradas** [comment]
Also having this issue after upgrading to `1.9.0`, but so far it seems other commands still work so this hasn't broken our implementation.

Still would be good to at least have this as a configuration setting we can toggle off.

Thanks for filing this issue @sbv-csis

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1514
