### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object [Python 3.9.6] on Both Windows and WSL

### ISSUE THREAD

**Issue by AlexGhanem** [rq/rq#1513]
I am trying to use rq to queue DB retrievals for a frontend dashboard to avoid timeout errors. 

The error I am getting is:

        Traceback (most recent call last):
          File "[..]\app copy.py", line 29, in <module>
            daily_count = q.enqueue(furnish_daily, data_full)
          File "[..]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local- 
          packages\Python39\site-packages\rq\queue.py", line 502, in enqueue
            return self.enqueue_call(
          File "[..]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local- 
          packages\Python39\site-packages\rq\queue.py", line 400, in enqueue_call
            return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
          File "[..]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local- 
          packages\Python39\site-packages\rq\queue.py", line 560, in enqueue_job
            job.save(pipeline=pipe)
          File "[..]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local- 
           packages\Python39\site-packages\rq\job.py", line 648, in save
            mapping = self.to_dict(include_meta=include_meta)
          File "[..]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local- 
          packages\Python39\site-packages\rq\job.py", line 590, in to_dict
            'data': zlib.compress(self.data),
          File "[..]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local- 
          packages\Python39\site-packages\rq\job.py", line 270, in data
            self._data = self.serializer.dumps(job_tuple)
           TypeError: cannot pickle '_thread.lock' object

my worker.py file:

```
import os

import redis
from rq import Worker, Queue, Connection

listen = ['high', 'default', 'low']

redis_url = os.getenv('REDISTOGO_URL', 'redis://localhost:6379')

conn = redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()
```

the function calls that seems to be causing the issue:

```
data_full = q.enqueue(furnish_stops)
daily_count = q.enqueue(furnish_daily, data_full)
```

note that data_full is a pandas dataframe from a BigQuery database that is passed to the next queue to get resampled data.

I have no idea what to do to solve this issue and have not found a fix anywhere besides a very vague answer on an old [thread ](https://github.com/rq/rq/issues/1413)

**Comment by AlexGhanem** [comment]
Update: installed python 3.7.11 and reinstalled all packages on it and still ran into the same exact error.

```
Traceback (most recent call last):
  File "app copy.py", line 29, in <module>
    daily_count = q.enqueue(furnish_daily, data_full)
  File "/home/alexis/.local/lib/python3.7/site-packages/rq/queue.py", line 507, in enqueue
    pipeline=pipeline
  File "/home/alexis/.local/lib/python3.7/site-packages/rq/queue.py", line 400, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "/home/alexis/.local/lib/python3.7/site-packages/rq/queue.py", line 560, in enqueue_job
    job.save(pipeline=pipe)
  File "/home/alexis/.local/lib/python3.7/site-packages/rq/job.py", line 648, in save
    mapping = self.to_dict(include_meta=include_meta)
  File "/home/alexis/.local/lib/python3.7/site-packages/rq/job.py", line 590, in to_dict
    'data': zlib.compress(self.data),
  File "/home/alexis/.local/lib/python3.7/site-packages/rq/job.py", line 270, in data
    self._data = self.serializer.dumps(job_tuple)
TypeError: can't pickle _thread.lock objects
```

**Comment by AlexGhanem** [comment]
update 2 lol: tried it with python 3.8.10 and still no luck. Same error.

I am running out of python versions to test.

**Comment by YingjieQiao** [comment]
just switch to another framework lol

**Comment by deduble** [comment]
#1413 
I have written a few things. `data_full`, I think it is clear that it has some RQ or BQ objects in it.

**Comment by deduble** [comment]
#1413 
I have mentioned a few things.

Try not the pass the job itself to the queue queue. Pass the relevant information about the job(like which q it is in, or its id etc.)

**Comment by selwin** [comment]
RQ uses pickle to serialize args and kwargs to Redis. In this case you're passing an object that can't be serialized by Python (from the error message, probably a Redis instance).

This is not due to a bug in RQ but a limitation in `pickle`. You may work around this using a custom serializer.
