### ISSUE TITLE
ERROR : Bulk Job Enqueueing

### ISSUE THREAD

**Issue by Rathan007** [rq/rq#1524]
I did the exact thing states in Docs about bulk enqueueing 
```python
jobs = q.enqueue_many(
  [
    Queue.prepare_data(count_words_at_url, 'http://nvie.com', job_id='my_job_id'),
    Queue.prepare_data(count_words_at_url, 'http://nvie.com', job_id='my_other_job_id'),
  ]
)
```
and when i run I got an error saying
```shell
Traceback (most recent call last):
  File "hello.py", line 18, in <module>
    jobs = q.enqueue_many(
  File "/mnt/g/OFFICE/PFA server/venv/lib/python3.8/site-packages/rq/queue.py", line 427, in enqueue_many
    jobs = [
  File "/mnt/g/OFFICE/PFA server/venv/lib/python3.8/site-packages/rq/queue.py", line 429, in <listcomp>
    self.create_job(
  File "/mnt/g/OFFICE/PFA server/venv/lib/python3.8/site-packages/rq/queue.py", line 312, in create_job
    job = self.job_class.create(
  File "/mnt/g/OFFICE/PFA server/venv/lib/python3.8/site-packages/rq/job.py", line 90, in create
    raise TypeError('{0!r} is not a valid args list'.format(args))
TypeError: 'http://nvie.com' is not a valid args list
```

Can anyone explain why im getting this error and how to solve this and how how to pass multiple jobs?

**Comment by rpkak** [comment]
You can try:

```python
jobs = q.enqueue_many(
  [
    Queue.prepare_data(count_words_at_url, ['http://nvie.com'], job_id='my_job_id'),
    Queue.prepare_data(count_words_at_url, ['http://nvie.com'], job_id='my_other_job_id'),
  ]
)
```

**Comment by rpkak** [comment]
Even if this issue is resolved the example in the docs doesn't work. I would suggest using `parse_args` in `prepare_data`.

**Comment by selwin** [comment]
Oh ok, I wasn't aware of this. Will reopen the issue.
