### ISSUE TITLE
failed to execute job from built-in scheduler

### ISSUE THREAD

**Issue by jiajunhuang** [rq/rq#1528]
```python
ERROR:rq.worker:Worker rq:worker:befe9eec17744a639eedd8811b4e17bb: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/data/py3/lib/python3.8/site-packages/rq/worker.py", line 591, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/data/py3/lib/python3.8/site-packages/rq/worker.py", line 660, in dequeue_job_and_maintain_ttl
    result = self.queue_class.dequeue_any(self._ordered_queues, timeout,
  File "/data/py3/lib/python3.8/site-packages/rq/queue.py", line 689, in dequeue_any
    queue_key, job_id = map(as_text, result)
  File "/data/py3/lib/python3.8/site-packages/rq/compat/__init__.py", line 62, in as_text
    raise ValueError('Unknown type %r' % type(v))
ValueError: Unknown type <class 'int'>
INFO:rq.worker:Unsubscribing from channel rq:pubsub:befe9eec17744a639eedd8811b4e17bb
```

**Comment by lowercase00** [comment]
Hey @jiajunhuang any sample you have to replicate this?
The `as_text` function indeed doesn't know how to handle `int`, perhaps it's something it could incorporate, but I just wonder how that `int` is getting there in the first place.
