### ISSUE TITLE
Python RQ Sample Error

### ISSUE THREAD

**Issue by anhdv1979** [rq/rq#1533]
I create 02 python programs as below
1. count_words.py
import requests
def count_words_at_url(url):
    resp = requests.get(url)
    return len(resp.text.split())
2.  sample.py
from redis import Redis
from rq import Queue
from count_words import count_words_at_url
q = Queue(connection=Redis())
result = q.enqueue(count_words_at_url, 'http://nvie.com')

when run rq worker, it shows error as below:
Traceback (most recent call last):   
File "/usr/local/lib/python3.7/dist-packages/rq/worker.py", line 1031, in perform_job     rv = job.perform()   
File "/usr/local/lib/python3.7/dist-packages/rq/job.py", line 749, in perform    
 self._result = self._execute()   
File "/usr/local/lib/python3.7/dist-packages/rq/job.py", line 772, in _execute     
result = self.func(*self.args, **self.kwargs)   
File "/usr/local/lib/python3.7/dist-packages/rq/job.py", line 225, in func     
return import_attribute(self.func_name)   
File "/usr/local/lib/python3.7/dist-packages/rq/utils.py", line 149, in import_attribute     
raise ValueError('Invalid attribute name: %s' % name) ValueError: Invalid attribute name: count_words.count_words_at_url | 1 minute ago |

**Comment by rpkak** [comment]
Where did you execute the worker? The worker needs to be started in the same place as the files you created.

**Comment by anhdv1979** [comment]
the rq worker install in /usr/local/bin from pip install rq. And I start command from terminal rq worker; then I use rq info it shows queues & 1 worker. However when I run sample.py (under /home/pi/Downloads) it shows error like above

**Comment by xxie12** [comment]
Hi, I am facing the same issue. How did you fix this? Thanks!
@anhdv1979
