### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by smm993** [rq/rq#1607]
```
rq worker -c rqsettings.py
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rq/cli/cli.py", line 87, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rq/cli/cli.py", line 228, in worker
    settings = read_config_file(cli_config.config) if cli_config.config else {}
  File "/usr/local/lib/python3.9/site-packages/rq/cli/helpers.py", line 34, in read_config_file
    settings = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 981, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rqsettings.py'; 'rqsettings' is not a package
```

**Comment by jgm1972** [comment]
How did you resolve this?  The command rq worker -c rqsettings.py works for me if I run it in the same directory as  rqsettings.py and worker.py or I omit  -c rqsettings.py. 
It used to work for me until a linux update.  Breaking on an update is strange because I am running rq and redis in a virtualenv which wasn't updated.
