### ISSUE TITLE
AttributeError: module has no attribute ''

### ISSUE THREAD

**Issue by cfal** [rq/rq#1614]
Since a few days ago, I'm seeing occasional failing jobs with this error:

```
Traceback (most recent call last):
  File "/app/python/lib/python3.9/site-packages/rq/worker.py", line 1043, in perform_job
    rv = job.perform()
  File "/app/python/lib/python3.9/site-packages/rq/job.py", line 814, in perform
    self._result = self._execute()
  File "/app/python/lib/python3.9/site-packages/rq/job.py", line 837, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/app/python/lib/python3.9/site-packages/rq/job.py", line 239, in func
    return import_attribute(self.func_name)
  File "/app/python/lib/python3.9/site-packages/rq/utils.py", line 158, in import_attribute
    attribute_owner = getattr(module, attribute_owner_name)

AttributeError: module 'api.services' has no attribute ''
```

I tried checking the FailedJobRegistry and seeing if `self.func_name` was not set correctly, but that didn't seem to be the case:

```
In [45]: j                                        
Out[45]: Job('67f06d2d-e37c-4236-9189-689ee95f1749', enqueued_at=datetime.datetime(2022, 1, 19, 20, 13, 29, 7818))

In [46]: j.func_name                              
Out[46]: 'api.services.logout'

In [47]: from rq.utils import import_attribute

In [48]: import_attribute(j.func_name)            
Out[48]: <function api.logout(account_id: str, retries=1)>
```

I don't see any RQ changes recently, and I'm not sure what could have caused it, or how to debug this.
Any feedback would be much appreciated. Thanks!

**Comment by caumons** [comment]
I'm experiencing exactly the same error randomly using the following versions under Python 3.10:

```
Flask==2.0.2
Flask-RQ2==18.3
rq==1.10.1
rq-scheduler==0.11.0
```

The traceback looks like this:

```
publisher-dev-rq-worker | 17:59:31 default: app.book.jobs.publish_today_chapter() (cron-publish-today-chapter)
publisher-dev-rq-worker | 17:59:31 Traceback (most recent call last):
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
publisher-dev-rq-worker |     rv = job.perform()
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/flask_rq2/job.py", line 41, in perform
publisher-dev-rq-worker |     return super(FlaskJob, self).perform()
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 821, in perform
publisher-dev-rq-worker |     self._result = self._execute()
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
publisher-dev-rq-worker |     result = self.func(*self.args, **self.kwargs)
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 238, in func
publisher-dev-rq-worker |     return import_attribute(self.func_name)
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/utils.py", line 157, in import_attribute
publisher-dev-rq-worker |     attribute_owner = getattr(module, attribute_owner_name)
publisher-dev-rq-worker | AttributeError: module 'app.book.jobs' has no attribute ''
publisher-dev-rq-worker | Traceback (most recent call last):
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
publisher-dev-rq-worker |     rv = job.perform()
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/flask_rq2/job.py", line 41, in perform
publisher-dev-rq-worker |     return super(FlaskJob, self).perform()
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 821, in perform
publisher-dev-rq-worker |     self._result = self._execute()
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
publisher-dev-rq-worker |     result = self.func(*self.args, **self.kwargs)
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 238, in func
publisher-dev-rq-worker |     return import_attribute(self.func_name)
publisher-dev-rq-worker |   File "/usr/local/lib/python3.10/site-packages/rq/utils.py", line 157, in import_attribute
publisher-dev-rq-worker |     attribute_owner = getattr(module, attribute_owner_name)
publisher-dev-rq-worker | AttributeError: module 'app.book.jobs' has no attribute ''
```

**Comment by caumons** [comment]
After further investigation, I've seen that the stack trace tried to execute a cron job called `app.book.jobs.publish_today_chapter()`. However, it had been renamed to `app.book.jobs.publish_todays_chapter()` a few days ago (note the `s` after `today`).

So, I've checked redis and I've found an entry called `rq:job:cron-publish-today-chapter`. There exists another one for the renamed job called `rq:job:cron-publish-todays-chapter`. So, I've deleted the entry matching the old name from redis and I hope  to have fixed the issue.

@cfal Have you recently renamed your failing job or changed its location path? Do you execute it as a cron job?

**Comment by cfal** [comment]
Nope, I don't execute it as a cron job. I did add an extra job when this started happening. The job that was failing was the previous job, named exactly the same.

**Comment by caumons** [comment]
If you've added a new job and the one failing is the previous one, then I'd check redis data if there is any incoherence. Maybe you could delete the keys for the failing job to be recreated again.
Good luck!

**Comment by selwin** [comment]
I think this is simply that you haven't restarted RQ after you made code changes in your projects.

**Comment by diogomatoschaves** [comment]
@selwin Is there a specific way to restart RQ?

**Comment by adarshpunj** [comment]
Why was this closed based on this assumption?

> I think this is simply that you haven't restarted RQ after you made code changes in your projects.
