### ISSUE TITLE
Retry does not work with the interval argument

### ISSUE THREAD

**Issue by charalamm** [rq/rq#1624]
I am trying to use the rq Retry functionality by following the rq [documentation](https://python-rq.org/docs/exceptions/) but it does not work when using the interval argument

python version: 3.8.0
rq version: 1.10.0

The somewhere.py
```
def my_func():
     print('Start...')
     asdsa # Here a NameError is raised
```
A script that enqueues my_func with the retry functionality
```
from redis import Redis
from rq import Retry, Queue

from somewhere import my_func


r = Redis("localhost",
    6379,
    socket_connect_timeout=1,
    decode_responses=True,
)

q = Queue(connection=r)
q.enqueue(my_func, retry=Retry(max=3, interval=10))
```

I was expecting to see the worker running my_func 3 times with 10 sec intervals in the between but it actually runs it only once. The worker output:
```
17:35:19 Worker rq:worker:1801215fdd1040b2aee962cccceff587: started, version 1.10.1
17:35:19 Subscribing to channel rq:pubsub:1801215fdd1040b2aee962cccceff587
17:35:19 *** Listening on default...
17:35:22 default: somewhere.my_func() (dc051976-598a-4863-8d15-6813c61d1377)
1
17:35:22 Traceback (most recent call last):
  File "/home/user/Documents/Projects/Aquacrop/aquacrop/aquacrop-api/env/lib/python3.8/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/user/Documents/Projects/Aquacrop/aquacrop/aquacrop-api/env/lib/python3.8/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/user/Documents/Projects/Aquacrop/aquacrop/aquacrop-api/env/lib/python3.8/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "./somewhere.py", line 3, in my_func
    somewhere
NameError: name 'somewhere' is not defined
Traceback (most recent call last):
  File "/home/user/Documents/Projects/Aquacrop/aquacrop/aquacrop-api/env/lib/python3.8/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/user/Documents/Projects/Aquacrop/aquacrop/aquacrop-api/env/lib/python3.8/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/user/Documents/Projects/Aquacrop/aquacrop/aquacrop-api/env/lib/python3.8/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "./somewhere.py", line 3, in my_func
    somewhere
NameError: name 'somewhere' is not defined
```
If I do not use the interval argument, the worker retries the function 3 times as expected.

Is this a bug or am I doing something wrong?

**Comment by selwin** [comment]
You'll need to run `rq worker --with-scheduler` to use the retry functionality. This is noted in the docs https://python-rq.org/docs/exceptions/#retrying-failed-jobs
