### ISSUE TITLE
`SimpleWorker` does not work on Windows as docs suggest due to `SIGALRM` signal not being implemented by OS

### ISSUE THREAD

**Issue by caffeinatedMike** [rq/rq#1625]
I have a dummy maintenance task that is scheduled to run once every minute using the below script (reduced for debugging)

```python
from subprocess import call
import sys
import time

import click
from flask import Flask
from redis import Redis
from rq import Queue
from rq_scheduler import Scheduler

def archive_logs():
   pass

@click.command("run-scheduler")
def run_scheduler():
    ret_val = call("rqscheduler --interval 5")  # check every 5 seconds while testing
    if ret_val != 0:
        sys.exit(ret_val)

@click.command("run-maintenance")
def run_maintenance_worker():
    from redis import Redis
    from rq import Queue, SimpleWorker
    maintenance_queue = Queue("maintenance-tasks", connection=Redis())
    worker = SimpleWorker([maintenance_queue], connection=maintenance_queue.connection)
    jobs = {}
    while True:
        try:
            for job in maintenance_queue.get_jobs():
                new_status = job.get_status(refresh=True)
                if job in jobs:
                    if jobs[job] != new_status:
                        print(job, ":", jobs[job], "->", new_status)
                else:
                    jobs[job] = new_status
                    print(job, ":", new_status)
            worker.work(burst=True)
            time.sleep(5)
        except KeyboardInterrupt:
            break

def create_app():
    app = Flask("Reproduce SimpleWorker Issue")
    # Setup background task components
    app.redis = Redis.from_url("redis://")
    # configure maintanence tasks
    maintenance = Scheduler(queue_name="maintenance-tasks", connection=app.redis)
    maintenance.cron("*/1 * * * *", archive_logs, id="archive_logs")
    app.cli.add_command(run_scheduler)
    app.cli.add_command(run_maintenance_worker)

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)
```

In order to monitor tasks scheduled/executed while developing locally, I'm using the `click` commands I registered in the script above.

# Steps to reproduce
1. In the first command prompt window run `flask run-scheduler`
2. In a second command prompt window run `flask start-maintenance`
3. Run the above file to start the flask app, which will place the cron job into the scheduler
4. Wait up to a minute for the job to be added to the `maintenance-tasks` queue
5. The below error occurs

```
<Job archive_logs: app.tasks.archive_logs()> : queued
11:19:06 Worker rq:worker:3da1229b65e340b2be74d8826bb72d7b: started, version 1.10.1
11:19:06 Subscribing to channel rq:pubsub:3da1229b65e340b2be74d8826bb72d7b
11:19:06 *** Listening on maintenance-tasks...
11:19:06 maintenance-tasks: app.tasks.archive_logs() (archive_logs)
11:19:06 Traceback (most recent call last):
  File "c:\users\mhill\pycharmprojects\daap_reporting_portal\venv\lib\site-packages\rq\worker.py", line 1060, in perform_job
    with self.death_penalty_class(timeout, JobTimeoutException, job_id=job.id):
  File "c:\users\mhill\pycharmprojects\daap_reporting_portal\venv\lib\site-packages\rq\timeouts.py", line 35, in __enter__
    self.setup_death_penalty()
  File "c:\users\mhill\pycharmprojects\daap_reporting_portal\venv\lib\site-packages\rq\timeouts.py", line 70, in setup_death_penalty
    signal.signal(signal.SIGALRM, self.handle_death_penalty)
AttributeError: module 'signal' has no attribute 'SIGALRM'
Traceback (most recent call last):
  File "c:\users\mhill\pycharmprojects\daap_reporting_portal\venv\lib\site-packages\rq\worker.py", line 1060, in perform_job
    with self.death_penalty_class(timeout, JobTimeoutException, job_id=job.id):
  File "c:\users\mhill\pycharmprojects\daap_reporting_portal\venv\lib\site-packages\rq\timeouts.py", line 35, in __enter__
    self.setup_death_penalty()
  File "c:\users\mhill\pycharmprojects\daap_reporting_portal\venv\lib\site-packages\rq\timeouts.py", line 70, in setup_death_penalty
    signal.signal(signal.SIGALRM, self.handle_death_penalty)
AttributeError: module 'signal' has no attribute 'SIGALRM'
11:19:06 Worker rq:worker:3da1229b65e340b2be74d8826bb72d7b: done, quitting
11:19:06 Unsubscribing from channel rq:pubsub:3da1229b65e340b2be74d8826bb72d7b
```

**Comment by caffeinatedMike** [comment]
The issue lies within the `Worker` class's usage of the `UnixSignalDeathPenalty` as the `death_penalty_class`
```python3
class Worker:
    redis_worker_namespace_prefix = 'rq:worker:'
    redis_workers_keys = worker_registration.REDIS_WORKER_KEYS
    death_penalty_class = UnixSignalDeathPenalty  # <= Culprit
    ...
```

The solution would be to create a `WindowsSignalDeathPenalty` class that subclasses `BaseDeathPenalty` and implements a Windows-friendly version of `setup_death_penalty` and `cancel_death_penalty`

**Comment by caffeinatedMike** [comment]
@selwin I believe I found a feasible solution to allow `SimpleWorker` to work again on Windows. Please see below and let me know your thoughts.
```python3
import threading

from rq.timeouts import BaseDeathPenalty, JobTimeoutException
from rq.worker import SimpleWorker


class WindowsSignalDeathPenalty(BaseDeathPenalty):

    def __init__(self, timeout, exception=JobTimeoutException, **kwargs):
        super().__init__(timeout, exception, **kwargs)
        self._timer = None
        self.reset_timer()

    def reset_timer(self):
        """Creates a new timer since timers can only be used once."""
        self._timer = threading.Timer(self._timeout, self.handle_death_penalty)

    def handle_death_penalty(self, signum, frame):
        raise self._exception(
            f"Task exceeded maximum timeout value ({self._timeout} seconds)"
        )

    def setup_death_penalty(self):
        """Sets up an alarm signal and a signal handler that raises
        an exception after the timeout amount (expressed in seconds).
        """
        self._timer.start()

    def cancel_death_penalty(self):
        """Removes the death penalty alarm and puts back the system into
        default signal handling.
        """
        self._timer.cancel()
        self.reset_timer()


class SimpleWindowsWorker(SimpleWorker):
    death_penalty_class = WindowsSignalDeathPenalty
```

Re-running the previously provided code using the `SimpleWindowsWorker` results in jobs being performed as expected.
```
19:43:08 Worker rq:worker:7880e746551f40bf80f1b016fe0c3719: started, version 1.10.1
19:43:08 Subscribing to channel rq:pubsub:7880e746551f40bf80f1b016fe0c3719
19:43:08 *** Listening on maintenance-tasks...
19:43:08 maintenance-tasks: app.tasks.archive_logs() (archive_logs)
19:43:08 maintenance-tasks: Job OK (archive_logs)
19:43:08 Result will never expire, clean up result key manually
19:43:08 Worker rq:worker:7880e746551f40bf80f1b016fe0c3719: done, quitting
19:43:08 Unsubscribing from channel rq:pubsub:7880e746551f40bf80f1b016fe0c3719
```

**Comment by selwin** [comment]
Have you tested this death penalty class on Linux as well? I'm obviously ok with improving `SimpleWorker` to also work on other platforms.

If this code has been sufficiently tested, please open a PR for this.
