### ISSUE TITLE
Worker exits with exception immediately on starting via django

### ISSUE THREAD

**Issue by purushnayak** [rq/rq#1653]
I have a worker that is run via django inside a docker container. The redis server is also a docker container. If I restart the both the containers then everything works for a while and then I start seeing this. Restarting the worker container exits immediately with the following error.

```
Attaching to my-container-1
[36mmy-container-1    |[0m 14:09:48 Worker rq:worker:ae17207462f84b5487d18e4b2949d998: started, version 1.10.1
[36mmy-container-1    |[0m 14:09:48 Subscribing to channel rq:pubsub:ae17207462f84b5487d18e4b2949d998
[36mmy-container-1    |[0m 14:09:48 *** Listening on adminq...
[36mmy-container-1    |[0m 14:09:48 Cleaning registries for queue: adminq
[36mmy-container-1    |[0m 14:36:48 Cleaning registries for queue: adminq
[36mmy-container-1    |[0m 15:03:48 Cleaning registries for queue: adminq
[36mmy-container-1    |[0m 15:30:48 Cleaning registries for queue: adminq
[36mmy-container-1    |[0m 15:57:49 Cleaning registries for queue: adminq
[36mmy-container-1    |[0m 16:00:47 Worker rq:worker:ae17207462f84b5487d18e4b2949d998: found an unhandled exception, quitting...
[36mmy-container-1    |[0m Traceback (most recent call last):
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 598, in work
[36mmy-container-1    |[0m     result = self.dequeue_job_and_maintain_ttl(timeout)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 670, in dequeue_job_and_maintain_ttl
[36mmy-container-1    |[0m     serializer=self.serializer)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/queue.py", line 709, in dequeue_any
[36mmy-container-1    |[0m     result = cls.lpop(queue_keys, timeout, connection=connection)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/queue.py", line 681, in lpop
[36mmy-container-1    |[0m     result = connection.blpop(queue_keys, timeout)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/commands/core.py", line 2385, in blpop
[36mmy-container-1    |[0m     return self.execute_command("BLPOP", *keys)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1222, in execute_command
[36mmy-container-1    |[0m     lambda error: self._disconnect_raise(conn, error),
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/retry.py", line 45, in call_with_retry
[36mmy-container-1    |[0m     return do()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1220, in <lambda>
[36mmy-container-1    |[0m     conn, command_name, *args, **options
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1195, in _send_command_parse_response
[36mmy-container-1    |[0m     return self.parse_response(conn, command_name, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1234, in parse_response
[36mmy-container-1    |[0m     response = connection.read_response()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 836, in read_response
[36mmy-container-1    |[0m     raise response
[36mmy-container-1    |[0m redis.exceptions.ResponseError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
[36mmy-container-1    |[0m Traceback (most recent call last):
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1930, in _execute_transaction
[36mmy-container-1    |[0m     response = self.parse_response(connection, "_")
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1998, in parse_response
[36mmy-container-1    |[0m     result = Redis.parse_response(self, connection, command_name, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1234, in parse_response
[36mmy-container-1    |[0m     response = connection.read_response()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 836, in read_response
[36mmy-container-1    |[0m     raise response
[36mmy-container-1    |[0m redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.
[36mmy-container-1    |[0m 
[36mmy-container-1    |[0m During handling of the above exception, another exception occurred:
[36mmy-container-1    |[0m 
[36mmy-container-1    |[0m Traceback (most recent call last):
[36mmy-container-1    |[0m   File "/var/www/html/backend/manage.py", line 21, in <module>
[36mmy-container-1    |[0m     main()
[36mmy-container-1    |[0m   File "/var/www/html/backend/manage.py", line 17, in main
[36mmy-container-1    |[0m     execute_from_command_line(sys.argv)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[36mmy-container-1    |[0m     utility.execute()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
[36mmy-container-1    |[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 328, in run_from_argv
[36mmy-container-1    |[0m     self.execute(*args, **cmd_options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 369, in execute
[36mmy-container-1    |[0m     output = self.handle(*args, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django_rq/management/commands/rqworker.py", line 130, in handle
[36mmy-container-1    |[0m     w.work(burst=options.get('burst', False), with_scheduler=options.get('with_scheduler', False), logging_level=level)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 637, in work
[36mmy-container-1    |[0m     self.register_death()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 337, in register_death
[36mmy-container-1    |[0m     p.execute()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2060, in execute
[36mmy-container-1    |[0m     lambda error: self._disconnect_raise_reset(conn, error),
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/retry.py", line 45, in call_with_retry
[36mmy-container-1    |[0m     return do()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2059, in <lambda>
[36mmy-container-1    |[0m     lambda: execute(conn, stack, raise_on_error),
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1933, in _execute_transaction
[36mmy-container-1    |[0m     raise errors[0][1]
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1923, in _execute_transaction
[36mmy-container-1    |[0m     self.parse_response(connection, "_")
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1998, in parse_response
[36mmy-container-1    |[0m     result = Redis.parse_response(self, connection, command_name, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1234, in parse_response
[36mmy-container-1    |[0m     response = connection.read_response()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 836, in read_response
[36mmy-container-1    |[0m     raise response
[36mmy-container-1    |[0m redis.exceptions.ReadOnlyError: Command # 1 (SREM rq:workers rq:worker:ae17207462f84b5487d18e4b2949d998) of pipeline caused error: You can't write against a read only replica.
[36mmy-container-1    |[0m Traceback (most recent call last):
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1930, in _execute_transaction
[36mmy-container-1    |[0m     response = self.parse_response(connection, "_")
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1998, in parse_response
[36mmy-container-1    |[0m     result = Redis.parse_response(self, connection, command_name, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1234, in parse_response
[36mmy-container-1    |[0m     response = connection.read_response()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 836, in read_response
[36mmy-container-1    |[0m     raise response
[36mmy-container-1    |[0m redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.
[36mmy-container-1    |[0m 
[36mmy-container-1    |[0m During handling of the above exception, another exception occurred:
[36mmy-container-1    |[0m 
[36mmy-container-1    |[0m Traceback (most recent call last):
[36mmy-container-1    |[0m   File "/var/www/html/backend/manage.py", line 21, in <module>
[36mmy-container-1    |[0m     main()
[36mmy-container-1    |[0m   File "/var/www/html/backend/manage.py", line 17, in main
[36mmy-container-1    |[0m     execute_from_command_line(sys.argv)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
[36mmy-container-1    |[0m     utility.execute()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 395, in execute
[36mmy-container-1    |[0m     self.fetch_command(subcommand).run_from_argv(self.argv)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 328, in run_from_argv
[36mmy-container-1    |[0m     self.execute(*args, **cmd_options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 369, in execute
[36mmy-container-1    |[0m     output = self.handle(*args, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/django_rq/management/commands/rqworker.py", line 130, in handle
[36mmy-container-1    |[0m     w.work(burst=options.get('burst', False), with_scheduler=options.get('with_scheduler', False), logging_level=level)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 561, in work
[36mmy-container-1    |[0m     self.register_birth()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/rq/worker.py", line 326, in register_birth
[36mmy-container-1    |[0m     p.execute()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2060, in execute
[36mmy-container-1    |[0m     lambda error: self._disconnect_raise_reset(conn, error),
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/retry.py", line 45, in call_with_retry
[36mmy-container-1    |[0m     return do()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 2059, in <lambda>
[36mmy-container-1    |[0m     lambda: execute(conn, stack, raise_on_error),
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1933, in _execute_transaction
[36mmy-container-1    |[0m     raise errors[0][1]
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1923, in _execute_transaction
[36mmy-container-1    |[0m     self.parse_response(connection, "_")
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1998, in parse_response
[36mmy-container-1    |[0m     result = Redis.parse_response(self, connection, command_name, **options)
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 1234, in parse_response
[36mmy-container-1    |[0m     response = connection.read_response()
[36mmy-container-1    |[0m   File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 836, in read_response
[36mmy-container-1    |[0m     raise response
[36mmy-container-1    |[0m redis.exceptions.ReadOnlyError: Command # 1 (DEL rq:worker:606744bb49dc4388a54a4c12d200f6b7) of pipeline caused error: You can't write against a read only replica.
[36mmy-container-1 exited with code 1
[0m
```

**Comment by selwin** [comment]
Juding from this error here:
> redis.exceptions.ReadOnlyError: Command # 1 (DEL rq:worker:606744bb49dc4388a54a4c12d200f6b7) of pipeline caused error: You can't write against a read only replica.
�[36mmy-container-1 exited with code 1

I think you're running RQ against a read only Redis server.
