### ISSUE TITLE
Getting DeserializationError, can someone help?

### ISSUE THREAD

**Issue by Amitdedhia6** [rq/rq#1714]
### Discussed in https://github.com/rq/rq/discussions/1713

<div type='discussions-op-text'>

<sup>Originally posted by **Amitdedhia6** September 26, 2022</sup>
Hi,

I am using redis queue for the first time. I am having many queues and I implemented using several classes. There is a base class and several derived classes for each queue. The job function is an abstract method defined in base class (having a dictionary as its only parameter) and implemented in derived class. I am getting deserialization error in worker. Not sure what is wrong here. Can someone help with useful pointers? Here is  skeleton code:

Env: WSL (on Windows 10), Python 3.9,  rq (most recent version)

```
class BaseQueue:
    def __init__(self, queue_name: str):
        self.queue_name = queue_name

    @lru_cache(maxsize=None)
    def _get_queue(self) -> Queue:
        return Queue(self.queue_name, connection=Redis.from_url(REDIS_URL)) 

    def enqueue(self, input_params, job_id):
       # NOTE - input_params is a dictionary 
        task_queue = self._get_queue()
        task_queue.enqueue(
            self.job_function,
            input_params,
            job_id=job_id,
            on_failure=report_failure
        )

    @abstractmethod
    def job_function(self, input_params):
        pass

    # other methods follow, they implement common functionalities

class Queue1(BaseQueue):
    def __init__(self):
        self.queue2 = Queue2()
        super().__init__("Queue1")


    def job_function(self, input_params):
	# all logic goes here
	# . . . . 
	self.queue2.enqueue(input_params=input_params,
                               job_id=self.get_current_job_id() + "_queue1")

class Queue2(BaseQueue):
    def __init__(self):
        super().__init__("Queue2)


    def job_function(self, input_params):
	# all logic goes here
	# . . . . 


### MAIN code
    main_queue = Queue1()
    job_id = "<something>"
    main_queue.enqueue(
        input_params,
        job_id=job_id
    )
```

And the error I get is (in worker):

```
11:14:33 Traceback (most recent call last):
  File "/home/amit/.pyenv/versions/3.9.5/lib/python3.9/site-packages/rq/job.py", line 282, in _deserialize_data
    self._func_name, self._instance, self._args, self._kwargs = self.serializer.loads(self.data)
  File "/home/amit/.pyenv/versions/3.9.5/lib/python3.9/site-packages/rq/serializers.py", line 21, in loads
    return json.loads(s.decode('utf-8'), *args, **kwargs)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amit/.pyenv/versions/3.9.5/lib/python3.9/site-packages/rq/worker.py", line 1063, in perform_job
    self.prepare_job_execution(job)
  File "/home/amit/.pyenv/versions/3.9.5/lib/python3.9/site-packages/rq/worker.py", line 936, in prepare_job_execution
    self.procline(msg.format(job.func_name, job.origin, time.time()))
  File "/home/amit/.pyenv/versions/3.9.5/lib/python3.9/site-packages/rq/job.py", line 317, in func_name
    self._deserialize_data()
  File "/home/amit/.pyenv/versions/3.9.5/lib/python3.9/site-packages/rq/job.py", line 285, in _deserialize_data
    raise DeserializationError() from e

```</div>

**Comment by Amitdedhia6** [comment]
Found the cause. I was using JSONSerializer when defined the worker object. However, objects in  Python are by default not serializable/de-serializable. Using default pickle bases serializer resolved the issue.
