### ISSUE TITLE
Exceptions Being Printed to Worker Log Stream twice

### ISSUE THREAD

**Issue by eswolinsky3241** [rq/rq#1741]
When an exception is raised by the enqueue() callback function, the stack trace is printed to the worker logs twice. This is a problem as we are importing these into our logging backend. 

For example, passing this function:
```
def run_script(script):
    raise Exception("FAILURE")
```

into this enqueue call:

```
queue = Queue(queue_name.lower(), connection=redis_client) 
queue.enqueue(hw.run_script)
```

will produce the following log stream on the worker:

```2022-12-17 12:51:12 17:51:12 Traceback (most recent call last):
2022-12-17 12:51:12   File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 1075, in perform_job
2022-12-17 12:51:12     rv = job.perform()
2022-12-17 12:51:12   File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 854, in perform
2022-12-17 12:51:12     self._result = self._execute()
2022-12-17 12:51:12   File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 877, in _execute
2022-12-17 12:51:12     result = self.func(*self.args, **self.kwargs)
2022-12-17 12:51:12   File "./hydra_wrapper.py", line 16, in run_script
2022-12-17 12:51:12     raise Exception("ERROR")
2022-12-17 12:51:12 Exception: ERROR
2022-12-17 12:51:12 Traceback (most recent call last):
2022-12-17 12:51:12   File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 1075, in perform_job
2022-12-17 12:51:12     rv = job.perform()
2022-12-17 12:51:12   File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 854, in perform
2022-12-17 12:51:12     self._result = self._execute()
2022-12-17 12:51:12   File "/usr/local/lib/python3.6/site-packages/rq/job.py", line 877, in _execute
2022-12-17 12:51:12     result = self.func(*self.args, **self.kwargs)
2022-12-17 12:51:12   File "./hydra_wrapper.py", line 16, in run_script
2022-12-17 12:51:12     raise Exception("ERROR")
2022-12-17 12:51:12 Exception: ERROR
```

How can I prevent this duplication of the stack trace? My first thought was that the failure triggered a retry, but I couldn't find documentation suggesting there's a default retry of one.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/rq/pull/1746
