### ISSUE TITLE
'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte

### ISSUE THREAD

**Issue by Flaviomsouza** [rq/rq#1748]
Hello guys.
I'm starting with python-rq, and when queuing my jobs I get the error 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte. can anybody help me?
On my machine it works, but when uploading to Heroku I get this error.

Logs:
2023-01-10T05:48:04.605338+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/rq/worker.py", line 605, in work
2023-01-10T05:48:04.605340+00:00 app[worker.1]:     result = self.dequeue_job_and_maintain_ttl(timeout)
2023-01-10T05:48:04.605341+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/rq/worker.py", line 674, in dequeue_job_and_maintain_ttl
2023-01-10T05:48:04.605342+00:00 app[worker.1]:     result = self.queue_class.dequeue_any(self._ordered_queues, timeout,
2023-01-10T05:48:04.605343+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/rq/queue.py", line 750, in dequeue_any
2023-01-10T05:48:04.605425+00:00 app[worker.1]:     raise e
2023-01-10T05:48:04.605552+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/rq/queue.py", line 740, in dequeue_any
2023-01-10T05:48:04.605553+00:00 app[worker.1]:     job = job_class.fetch(job_id, connection=connection, serializer=serializer)
2023-01-10T05:48:04.605554+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/rq/job.py", line 372, in fetch
2023-01-10T05:48:04.605555+00:00 app[worker.1]:     job.refresh()
2023-01-10T05:48:04.605555+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/rq/job.py", line 615, in refresh
2023-01-10T05:48:04.605556+00:00 app[worker.1]:     data = self.connection.hgetall(self.key)
2023-01-10T05:48:04.605570+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/commands/core.py", line 4854, in hgetall
2023-01-10T05:48:04.605572+00:00 app[worker.1]:     return self.execute_command("HGETALL", name)
2023-01-10T05:48:04.605573+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/client.py", line 1258, in execute_command
2023-01-10T05:48:04.605573+00:00 app[worker.1]:     return conn.retry.call_with_retry(
2023-01-10T05:48:04.605573+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
2023-01-10T05:48:04.605574+00:00 app[worker.1]:     return do()
2023-01-10T05:48:04.605575+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/client.py", line 1259, in <lambda>
2023-01-10T05:48:04.605575+00:00 app[worker.1]:     lambda: self._send_command_parse_response(
2023-01-10T05:48:04.605576+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/client.py", line 1235, in _send_command_parse_response
2023-01-10T05:48:04.605577+00:00 app[worker.1]:     return self.parse_response(conn, command_name, **options)
2023-01-10T05:48:04.605577+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/client.py", line 1275, in parse_response
2023-01-10T05:48:04.605578+00:00 app[worker.1]:     response = connection.read_response()
2023-01-10T05:48:04.605578+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 848, in read_response
2023-01-10T05:48:04.605578+00:00 app[worker.1]:     response = self._parser.read_response(disable_decoding=disable_decoding)
2023-01-10T05:48:04.605579+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 335, in read_response
2023-01-10T05:48:04.605579+00:00 app[worker.1]:     result = self._read_response(disable_decoding=disable_decoding)
2023-01-10T05:48:04.605579+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 383, in _read_response
2023-01-10T05:48:04.605580+00:00 app[worker.1]:     response = [
2023-01-10T05:48:04.605580+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 384, in <listcomp>
2023-01-10T05:48:04.605580+00:00 app[worker.1]:     self._read_response(disable_decoding=disable_decoding)
2023-01-10T05:48:04.605580+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 388, in _read_response
2023-01-10T05:48:04.605581+00:00 app[worker.1]:     response = self.encoder.decode(response)
2023-01-10T05:48:04.605581+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/redis/connection.py", line 121, in decode
2023-01-10T05:48:04.605581+00:00 app[worker.1]:     value = value.decode(self.encoding, self.encoding_errors)
2023-01-10T05:48:04.605582+00:00 app[worker.1]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
2023-01-10T05:48:04.691357+00:00 app[worker.1]: 05:48:04 Unsubscribing from channel rq:pubsub:284da221aa514a13acd28e8858336081

**Comment by deep-adeshraa** [comment]
Facing similar issue while doing `Worker.work`. 
Please find logs attached below 
```
Traceback (most recent call last):
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/rq/worker.py", line 510, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/rq/worker.py", line 576, in dequeue_job_and_maintain_ttl
    result = self.queue_class.dequeue_any(self.queues, timeout,
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/rq/queue.py", line 550, in dequeue_any
    job = job_class.fetch(job_id, connection=connection)
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/rq/job.py", line 303, in fetch
    job.refresh()
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/rq/job.py", line 512, in refresh
    data = self.connection.hgetall(self.key)
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/client.py", line 2717, in hgetall
    return self.execute_command('HGETALL', name)
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/connection.py", line 350, in read_response
    response = [self.read_response() for i in xrange(length)]
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/connection.py", line 350, in <listcomp>
    response = [self.read_response() for i in xrange(length)]
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/connection.py", line 352, in read_response
    response = self.encoder.decode(response)
  File "/home/d/ubico/ubico-monorepo/ubico-api/env/lib/python3.9/site-packages/redis/connection.py", line 126, in decode
    value = value.decode(self.encoding, self.encoding_errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
```

**Comment by lowercase00** [comment]
@deep-adeshraa @Flaviomsouza perhaps there's some non ascii chars on the job that's being enqueued?

```python
>>> b'\x9c'.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 0: invalid start byte

>>> b'\x9c'.decode('cp1252')
'œ'
```

- Do you have an example job where this can be replicated?
- Does this happen with the default serializer (`pickle`) or are you using a custom one?
- Which version are you guys using (`rq`, `redis` and `redis-py`)?

The error seems to be raised by Redis (py), so we actually don't even get the data before the exception. I think we are encoding most of what we are sending to Redis with `utf-8`, what's confusing (to me) is how that happened in the first place.

**Comment by mukhamux** [comment]
@Flaviomsouza look hear: https://github.com/rq/rq/issues/1188
