### ISSUE TITLE
v1.14 breaks rq-scheduler

### ISSUE THREAD

**Issue by sagi-sensorz** [rq/rq#1893]
rq-scheduler produces the following error on startup since rq was upgraded to v1.14:

```
Traceback (most recent call last):
  File "/usr/local/bin/rqscheduler", line 5, in <module>
    from rq_scheduler.scripts.rqscheduler import main
  File "/usr/local/lib/python3.11/site-packages/rq_scheduler/__init__.py", line 3, in <module>
    from .scheduler import Scheduler
  File "/usr/local/lib/python3.11/site-packages/rq_scheduler/scheduler.py", line 18, in <module>
    from .utils import from_unix, to_unix, get_next_scheduled_time, rationalize_until
  File "/usr/local/lib/python3.11/site-packages/rq_scheduler/utils.py", line 8, in <module>
    from rq.utils import ColorizingStreamHandler
ImportError: cannot import name 'ColorizingStreamHandler' from 'rq.utils' (/usr/local/lib/python3.11/site-packages/rq/utils.py)
```

Since rq-scheduler by default takes the latest rq version, it means rq-scheduler doesn't work anymore via pip install...

**Comment by selwin** [comment]
@sagi-sensorz mind opening a PR at rq-scheduler's repo? The fix should be simple and somewhat similar to this https://github.com/rq/django-rq/pull/595/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR381

**Comment by sagi-sensorz** [comment]
@selwin Thanks for the quick fix, unfortunately I didn't have time for this.
