### ISSUE TITLE
AttributeError: 'Blueprint' object has no attribute 'before_app_first_request'

### ISSUE THREAD

**Issue by zhangguoqiang666** [rq/rq#1927]
Traceback (most recent call last):
  File "/usr/local/bin/rq-dashboard", line 5, in <module>
    from rq_dashboard.cli import main
  File "/usr/local/lib/python3.8/dist-packages/rq_dashboard/__init__.py", line 3, in <module>
    from .web import blueprint
  File "/usr/local/lib/python3.8/dist-packages/rq_dashboard/web.py", line 68, in <module>
    @blueprint.before_app_first_request
AttributeError: 'Blueprint' object has no attribute 'before_app_first_request'

**Comment by zhangguoqiang666** [comment]
this isuuse happen when use rq-dashboard

**Comment by nhoening** [comment]
I got this error when upgrading Flask:

    -flask==2.1.2
    +flask==2.3.2

Anyway, the issue in the actual rq-dashboard repo is [here](https://github.com/Parallels/rq-dashboard/issues/417).
