### ISSUE TITLE
A more compact exception log

### ISSUE THREAD

**Issue by mjnaderi** [rq/rq#1935]
Hi,

When an exception raises, RQ runs this:

https://github.com/rq/rq/blob/0b5a90adac2f51e257a2ec3ec9e954a4b0d52f52/rq/worker.py#L1501

and prints an error log containing job id, function name,  and the stack trace:

```
[2023-06-05 13:08:47,596] ERROR    [Job 488f3efd-6ce1-47a9-9c24-00f825b6654c]: exception raised while executing (app.tasks.send_email)
Traceback (most recent call last):
  File "/home/naderi/.pyenv/versions/myproject/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/home/naderi/.pyenv/versions/myproject/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/home/naderi/.pyenv/versions/myproject/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/naderi/myrepo/app/tasks.py", line 42, in send_email
    raise SendEmailFailed(f"Failed (tried {try_count} times)")
app.tasks.SendEmailFailed: Failed (tried 3 times)
```

This default behavior is OK and makes sense. But it would be nice to be able to customize the message format. In my case, the stack trace is not important for me and it just clutters my log file. I'm looking for a way to have a single-line log (only print job id, function name, exception class, exception message):

```
[2023-06-05 13:08:47,596] ERROR    [Job 488f3efd-6ce1-47a9-9c24-00f825b6654c]: exception raised while executing (app.tasks.send_email): app.tasks.SendEmailFailed: Failed (tried 3 times)
```

A way to customize the error log format, or a way to override the default exception handler would be nice.

**Comment by mjnaderi** [comment]
I came up with this solution. It is a bit hacky though because of the monkey-patch.

```python
from rq.job import Job
from rq.worker import Worker


class CustomRQWorker(Worker):
    def handle_job_failure(self, job: Job, queue, started_job_registry=None, exc_string=""):
        self.__job_retries_left = job.retries_left
        return super().handle_job_failure(job, queue, started_job_registry, exc_string)

    def handle_exception(self, job: Job, *exc_info):
        """
        Customize the exception log format by monkey-patching self.log.error.
        We do this to have more compact exception log messages.
        The full traceback is available in Sentry.

        Related issue: https://github.com/rq/rq/issues/1935
        """

        original_log_error = self.log.error

        def custom_log_error(*args, **kwargs):
            stype = exc_info[0].__qualname__
            smod = exc_info[0].__module__
            if smod not in ("__main__", "builtins"):
                if not isinstance(smod, str):
                    smod = "<unknown>"
                stype = smod + "." + stype
            exception_str = stype + (f": {exc_info[1]}" if str(exc_info[1]) else "")

            extra = kwargs["extra"]

            original_log_error(
                "Exception : job=%s func=%s retries_left=%d exc=%s",
                job.id,
                extra.get("func"),
                self.__job_retries_left,
                exception_str,
                extra=extra,
            )

        # apply the monkey-patch
        self.log.error = custom_log_error
        # run the original handle_exception
        super().handle_exception(job, *exc_info)
        # restore the original method
        self.log.error = original_log_error
```

**Comment by selwin** [comment]
Agreed that this maybe nice. Would a `exception_formatter` argument to `work()` be enough?

**Comment by mjnaderi** [comment]
Hi @selwin. I'm not sure actually.
I will be happy if I can somehow pass the exception format through a CLI argument to `rq worker` command.
Anyway, it would be nice to have a separate method on Worker class for exception formatting (which runs the `self.log.error` line), so we can simply extend the worker class and override that method without monkey patching.
