### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yuanjie-ai** [rq/rq#1942]
ResponseError: CROSSSLOT Keys in request don't hash to the same slot

**Comment by selwin** [comment]
I haven't seen this error before. Can you elaborate on how to reproduce this?

**Comment by nsht** [comment]
This occurs when Redis is operated in cluster mode.
I can replicate this issue using AWS ElastiCache Redis configured in cluster mode with RQ.
The worker fails as soon as it starts. Attached is a stack trace for the same. 


More Context on the error:
https://hackernoon.com/resolving-the-crossslot-keys-error-with-redis-cluster-mode-enabled


```python
worker-1  | Traceback (most recent call last):
worker-1  |   File "/app/worker.py", line 19, in <module>
worker-1  |     worker.work(with_scheduler=True)
worker-1  |   File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 403, in work
worker-1  |     self.bootstrap(logging_level, date_format, log_format)
worker-1  |   File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 568, in bootstrap
worker-1  |     self.register_birth()
worker-1  |   File "/usr/local/lib/python3.9/site-packages/rq/worker.py", line 821, in register_birth
worker-1  |     p.execute()
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1478, in execute
worker-1  |     return conn.retry.call_with_retry(
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
worker-1  |     return do()
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1479, in <lambda>
worker-1  |     lambda: execute(conn, stack, raise_on_error),
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1348, in _execute_transaction
worker-1  |     response = self.parse_response(connection, "_")
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1416, in parse_response
worker-1  |     result = Redis.parse_response(self, connection, command_name, **options)
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 553, in parse_response
worker-1  |     response = connection.read_response()
worker-1  |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 524, in read_response
worker-1  |     raise response
worker-1  | redis.exceptions.ResponseError: CROSSSLOT Keys in request don't hash to the same slot
worker-1 exited with code 1```

**Comment by ethanseow** [comment]
Any updates on this ^^^ I have the exact same issue. Might switchover to rabbit mq or aws sqs if this is a problem

**Comment by selwin** [comment]
RQ does not support Redis cluster yet. PR ti fix this welcome :)

**Comment by sc-sribat** [comment]
Will using this library under RQ help?
https://pypi.org/project/redis-py-cluster/

**Comment by mertcanaliciaaron** [comment]
Is there any solution for this problem, like using {...} pattern?
