### ISSUE TITLE
The latest version encounters an error report, and the worker exits abnormally

### ISSUE THREAD

**Issue by Miracles666** [rq/rq#1943]
I don't know what caused it
12:36:58 Worke rxxxx_0: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 423, in work
    result = self.dequeue_job_and_maintain_ttl(timeout, max_idle_time)
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 593, in dequeue_job_and_maintain_ttl
    self.run_maintenance_tasks()
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 553, in run_maintenance_tasks
    self.clean_registries()
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 318, in clean_registries
    clean_intermediate_queue(self, queue)
  File "/usr/local/lib/python3.8/dist-packages/rq/maintenance.py", line 24, in clean_intermediate_queue
    worker.handle_job_failure(job, queue, exc_string='Job was stuck in the intermediate queue.')
  File "/usr/local/lib/python3.8/dist-packages/rq/worker.py", line 1306, in handle_job_failure
    self.log.debug('Handling failed execution of job %s', job.id)
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by Miracles666** [comment]
@selwin

**Comment by selwin** [comment]
Will take a look at this

**Comment by Miracles666** [comment]
I set the failed callback function on_ failure, but if the worker exits, the function will not run.

**Comment by Miracles666** [comment]
hi bro @selwin  It seems that I may have found the issue. I have assigned the same job_id to two different tasks. Would completing one task affect the other task?

**Comment by Miracles666** [comment]
Would this error cause the worker to exit abnormally?

**Comment by selwin** [comment]
Yes it may. RQ is not designed for multiple jobs with the same ID to be executed simultaneously. If this causes error, you should try downgrading to an older version while I try to work on a patch sometime in the next few days.

**Comment by Miracles666** [comment]
only latest version support Callback(on_stopped='my_callback) this feature @selwin

**Comment by selwin** [comment]
@Miracles666 can you see if https://github.com/rq/rq/commit/6cfb5a60125ba906604ffc0526a1026b5dc85443 fixes your issue?

**Comment by Miracles666** [comment]
hey bro！ @selwin I tried submitting two test tasks with the same job_id. The test function is as follows:
`def test():
    time.sleep(10)
    print("test run success!")`

![image](https://github.com/rq/rq/assets/40236845/cc83ec38-9bbf-4a10-9aea-918bbca9f645)

It seems that there are no errors occurring. Does this mean the issue has been resolved?     


But in actual projects, I don't know if I will encounter it or not. I will let you know when I do.@selwin

**Comment by iantanwx** [comment]
@selwin we were having this issue and upgrade to `1.15.1` fixed it. Thanks!
