### ISSUE TITLE
ValueError: Unknown type <class 'NoneType'>

### ISSUE THREAD

**Issue by Frissi0n** [rq/rq#1953]
When executing rq worker, I get the following error 

```
rq, version 1.14.1
rq worker --with-scheduler
Traceback (most recent call last):
  File "/opt/homebrew/bin/rq", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rq/cli/helpers.py", line 424, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rq/cli/cli.py", line 251, in worker
    cleanup_ghosts(cli_config.connection)
  File "/opt/homebrew/lib/python3.11/site-packages/rq/contrib/legacy.py", line 20, in cleanup_ghosts
    for worker in Worker.all(connection=conn):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rq/worker.py", line 257, in all
    workers = [
              ^
  File "/opt/homebrew/lib/python3.11/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "/opt/homebrew/lib/python3.11/site-packages/rq/worker.py", line 685, in find_by_key
    worker.refresh()
  File "/opt/homebrew/lib/python3.11/site-packages/rq/worker.py", line 1041, in refresh
    queues = as_text(queues)
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rq/utils.py", line 58, in as_text
    raise ValueError('Unknown type %r' % type(v))
ValueError: Unknown type <class 'NoneType'>
```

**Comment by Frissi0n** [comment]
Works on 1.15.1
