### ISSUE TITLE
example of rq with flask blueprint app

### ISSUE THREAD

**Issue by blacksteel1288** [rq/rq#1975]
Hi,

Since it looks like Flask-RQ2 is no longer being maintained, is there a new or updated guide or example for how to use RQ with a Flask Blueprint app?

Thank you!

**Comment by ddipp** [comment]
Hi!

For example.
config.py:

```
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 3
```

\_\_init\_\_.py:
```
import redis
import rq
from flask import Flask

app = Flask(__name__)

try:
    app.config.from_object('app.productionconfig')
except ImportError:
    app.config.from_object('app.config')

app.redis = redis.from_url('redis://{0}:{1}/{2}'.format(app.config['REDIS_HOST'], app.config['REDIS_PORT'], app.config['REDIS_DB']))
app.task_queue = rq.Queue('default', connection=app.redis)

from app.v1.views import v01  # noqa

app.register_blueprint(v01, url_prefix='/mlc/api/v1')
```

v01/views.py:
```
from rq.job import Job
from flask import Blueprint, jsonify, current_app, send_file

v01 = Blueprint('v1', __name__)

@v01.route('/profile_get/<string:filename>')
def profile_get(filename):
    return send_file(current_app.config['CACHE_DIR_PROFILE'] / filename, mimetype='image/png')


@v01.route('profile_add_task/<float:la_a>/<float:lo_a>/<float:la_b>/<float:lo_b>')
def profile_add_task(la_a: float, lo_a: float, la_b: float, lo_b: float):
    rq_job = current_app.task_queue.enqueue('app.v1.tasks.profile', la_a, lo_a, la_b, lo_b, current_app.config['CACHE_DIR_PROFILE'])
    return jsonify(job_id=rq_job.id,
                   job_status=rq_job.get_status(),
                   job_result=rq_job.result)
```

**Comment by blacksteel1288** [comment]
Thanks, but not what I was looking for.  I should have been clearer in my original post.

I'm looking for an example of using rq in an [application factory](https://flask.palletsprojects.com/en/2.3.x/patterns/appfactories/) style app, that also uses blueprints, which it seems that Flask-RQ2 supported previously.

I haven't been able to figure out how to initialize the rq object correctly and use it within a blueprint, and also how start the workers, with the app context.

Here's what I started with (not complete)

```
__init__.py

from flask import Flask, session, request, abort
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from flask_mongoengine import MongoEngine
from flask_executor import Executor
from flask_mail import Mail
from rq import Queue

db = SQLAlchemy()
ma = Marshmallow()
mongo_db = MongoEngine()
executor = Executor()
mail = Mail()
rq = Queue()


def register_extensions(app):
    db.init_app(app)
    ma.init_app(app)
    mongo_db.init_app(app)
    executor.init_app(app)
    mail.init_app(app)
    rq.init_app(app)

...
```

```
config.py

class Config(object):
    RQ_REDIS_URL = 'redis://localhost:6379/0'

...
```

Thank you!

**Comment by jpsnyder** [comment]
For the workers, I made a `create_worker()` factory method that will call the `create_app()` factory method.

```python
# rq_worker.py
from . import create_worker

if __name__ == "__main__":
    worker = create_worker()
    worker.work()
```

```python
# app/__init__.py
import flask
import rq

def create_app():
    ...
    
def create_worker():
    app = create_app()
    worker = rq.Worker(
         ["default"]
        connection=app.extensions["redis"],
        default_worker_ttl=app.config["RQ_WORKER_TTL"],
        default_result_ttl=app.cofnig["RQ_RESULT_TTL"],
    )
    return worker
```

**Comment by blacksteel1288** [comment]
I'm still not able to get this to work in my blueprint app, which is a REST API.  Whenever I call an enqueue, I get a `"RuntimeError: Working outside of application context."` in the worker console.  

I am using a `with app.app_context():` before calling the enqueue.

Here's my setup:

```
worker.py

from app import create_worker
from config import config_dict
from os import environ

get_config_mode = environ.get('CONFIG_MODE')

try:
    config_mode = config_dict[get_config_mode.capitalize()]
except KeyError:
    exit('Error: Invalid CONFIG_MODE environment variable entry.')

if __name__ == "__main__":
    worker = create_worker(config_mode)
    worker.work()
```

```
__init__.py

...
from redis import Redis
import rq
...

def create_app(config):
    app = Flask(__name__,
                static_url_path='',
                static_folder='op/static')
    app.config.from_object(config)
    app.redis = Redis.from_url(app.config['REDIS_URL'])
    app.task_queue = rq.Queue('tasks', connection=app.redis)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    configure_logs(app)
    return app


def create_worker(config):
    app = create_app(config)
    worker = rq.Worker('tasks', connection=app.redis)
    return worker

```

```
app.op.routes.py

...
from . import api_op
from .process import *
from flask_restx import Resource, reqparse, fields, inputs
from flask import current_app as app
...

@api_op.route('/process')
class Process(Resource):
    def post(self):
        process_refresh_parser = reqparse.RequestParser()
        process_refresh_parser.add_argument('action', type=str, required=True, location='args')
        process_refresh_parser.add_argument('tid', type=int, required=True, location='args')
        args = process_refresh_parser.parse_args()
        if args.action == "run":
            # rq
            with app.app_context():
                job = app.task_queue.enqueue(process_refresh, args.tid)
        return {"message": "OK:  Process started"}
```

output from worker

```
python worker.py

13:07:52 Worker rq:worker:e17ce6e32e63466e98a7112f82382b95 started with PID 51578, version 1.15.1
13:07:52 Subscribing to channel rq:pubsub:e17ce6e32e63466e98a7112f82382b95
13:07:52 *** Listening on tasks...
13:07:57 tasks: app.op.process.process_refresh(1) (37d1034b-80c0-47fd-be95-dbe0bc293c8b)
13:07:57 [Job 37d1034b-80c0-47fd-be95-dbe0bc293c8b]: exception raised while executing (app.op.process.process_refresh)
Traceback (most recent call last):
  File "/.../api/venv/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/.../api/venv/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/.../api/venv/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/.../api/app/op/process.py", line 108, in process_refresh
    app.logger.info(f'[tid {tid}] [refresh] update started.')
  File "/.../api/venv/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/.../api/venv/lib/python3.10/site-packages/werkzeug/local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.


```

Note, this same process runs correctly in the background as a flask_executor task.  I'm attempting to migrate to rq instead.

**Comment by ccrvlh** [comment]
I've never used RQ directly attached to Flask like what you're doing, so I wouldn't  know exactly what might be the issue.
Quickly looking at the snippet, it seems like you have two apps? One is being created inside the `create_worker` function, and the other you're probably passing to uWSGI (to actually run the API). If that's the case, then you are indeed working outside of the application context (inside the API server context, outside the worker's app context). Is there any specific reason you want RQ _within_ Flask, rather than just a regular class instance?

**Comment by blacksteel1288** [comment]
Yes, I was initially attempting to follow the pattern from Flask-RQ2, which is no longer maintained.  Then found this post https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxii-background-jobs/page/2`https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xxii-background-jobs/page/2` which was helpful for Flask apps with RQ.

In the end, answering my own question, but the solution for me, in this pattern, was to add the `with app.app_context():` to the `create_worker`.  Like this:

```
__init__.py

...
from redis import Redis
import rq
...

def create_app(config):
    app = Flask(__name__,
                static_url_path='',
                static_folder='op/static')
    app.config.from_object(config)
    app.redis = Redis.from_url(app.config['REDIS_URL'])
    app.task_queue = rq.Queue('tasks', connection=app.redis)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    configure_logs(app)
    return app


def create_worker(config):
    app = create_app(config)
    with app.app_context():
      worker = rq.Worker('tasks', connection=app.redis)
    return worker
```

After doing this, the functions ran successfully in the queue, and I was even able to remove the `with app.app_context():` from the function call.

However, since I'm using session data in some functions, I had to update the context to include a fake session by doing `with app.test_request_context('/'):`

After some refactoring, my final solution looks like this:

```
__init__.py

...
from redis import Redis
from rq import Worker


db = SQLAlchemy()
ma = Marshmallow()
mongo_db = MongoEngine()
executor = Executor()
mail = Mail()


def register_extensions(app):
    db.init_app(app)
    ma.init_app(app)
    mongo_db.init_app(app)
    executor.init_app(app)
    mail.init_app(app)
    app.redis = Redis.from_url(app.config['REDIS_URL'])


def create_app(config):
    app = Flask(__name__,
                static_url_path='',
                static_folder='op/static')
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    configure_logs(app)
    return app


def create_worker(config):
    app = create_app(config)
    with app.test_request_context('/'):
        worker = Worker('tasks', connection=app.redis)
        worker.work()
    return worker
```

And, then I moved the creation of the queues into the route functions.

However, I would like to know the proper way to pass session data into an rq task.  Since that's a new topic, I'll create another post.

Thank you!

**Comment by jpsnyder** [comment]
Unsure if this helps, but one thing I did was make the queue a global variable in the `tasks.py` module so can just use the queue without woryying about trying to obtain the app itself.

```python
# tasks.py

import rq

queue: rq.Queue

def init_app(app):
    global queue
    redis = Redis.from_url(app.config["REDIS_URI"])
    app.extensions["redis"] = redis
    queue = rq.Queue(connection=redis)
    

def some_task(upload_id):
    # do work
    ...    


def do_stuff(primary_id):
    queue.enqueue(some_task, primary_id)
```


```python
# app/__init__.py

from my_project.app import tasks

def create_app():
    app = flask.Flask(__name__)
    app.config.from_object("my_project.app.config")
    app.app_context.push()
    
    tasks.init_app(app)
    return app
```

(Maybe now that I look at this again, perhaps doing `app.app_context.push()` in the factory method was key)

**Comment by blacksteel1288** [comment]
As a footnote question to those following or contributing to this discussion -- I am wondering, is there a correct pattern for where to place the `with app.app_context():`?  I've seen it working both ways now, but not sure which is better.

1.  Place it before the call to start the worker, so the worker has the context all the time while running for any jobs sent to it (e.g.
```
def create_worker(config):
    app = create_app(config)
    with app.app_context():
      worker = rq.Worker('some_queue', connection=app.redis)
    return worker
```

2.  Place it before the call to add a job to a queue, so the job has the context, and the worker has none by itself (e.g.
```
with app.app_context():
    job = app.task_queue.enqueue(some_function)
```
