### ISSUE TITLE
Task got Future attached to a different loop

### ISSUE THREAD

**Issue by 5-30** [rq/rq#1986]
## My code :

First, in order to queue elements, I use this (1 queue per user, each queue gets a worker automatically)
`queues_with_workers = set()

redis = Redis()

def worker_func(queue):
    worker = Worker(queues=[queue], connection=redis)
    worker.work()

async def enqueue_task(playerRoles, interaction, user_id, function, *args, **kwargs):
    queue = Queue(f'user_{user_id}', connection=redis)
    print(f"queue à {len(queue)}, jobs à {queue.started_job_registry.count}, rôles à {playerRoles}")
    if "20v/j" in playerRoles and len(queue) + queue.started_job_registry.count > 1:
        await interaction.followup.send("Vous profitez de l'offre '5 vidéos par jour', qui ne permet que deux générations à la fois. Merci d'attendre la fin de ces dernières :thumbsup:", ephemeral=True)
        return
    elif "5v/j" in playerRoles and len(queue) + queue.started_job_registry.count > 0:
        await interaction.followup.send("Vous profitez de l'offre '5 vidéos par jour', qui ne permet qu'une génération à la fois. Merci d'attendre la fin de cette dernière :thumbsup:", ephemeral=True)
        return
    else:
        queue.enqueue(function, **kwargs)
        if queue.name not in queues_with_workers:
            worker_process = Process(target=worker_func, args=(queue))
            worker_process.start()
            queues_with_workers.add(queue.name)`
            
In my code, I use it to run "generate_video" (which is imported from another module). Here is the sais function :

`async def generate_video(link, start, end, satisornot, user, titre, fili, auto=False):
    try:
        await genwarning(user)
        result = await generatemod(link, start, end, satisornot, user, titre, fili, auto=auto)
        await user.send(result)
    except Exception as e:
        await errorwarning(str(e) + f"** - Erreur lors de la génération d'un reupload pour <@{user}>**")
        remove_or_update_user(str(user.id))
        await user.send("Une erreur s'est produite ! Vérifiez que les données soient entrées au bon format. Si cela ne fonctionne pas, contactez N530.")
`

The issue being that I get an error when attempting to run this command:
`20:16:16 [Job 3e619d13-35ad-4165-9b94-77b21bd9cf82]: exception raised while executing (discordwrapper.generate_video)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.9/dist-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.9/dist-packages/rq/job.py", line 1318, in _execute
    coro_result = loop.run_until_complete(result)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/discordwrapper.py", line 14, in generate_video
    await errorwarning(str(e) + f"** - Erreur lors de la génération d'un reupload pour <@{user}>**")
  File "/root/discordwrapper.py", line 44, in errorwarning
    await channel.send(f"Erreur: " + msg)
  File "/usr/local/lib/python3.9/dist-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 625, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
RuntimeError: Task <Task pending name='Task-80' coro=<generate_video() running at /root/discordwrapper.py:14> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending cb=[shield.<locals>._outer_done_callback() at /usr/lib/python3.9/asyncio/tasks.py:903]> attached to a different loop`

Would you happen to know why that is? I've spent my whole day trying to make things work, but I'm stuck here and I don't have a clue what to do. We can see it _seem_ to happen as soon as I try to send an error message to my Discord server, in the "errorwarning" function:
`
async def errorwarning(msg):
    channel = bot.get_channel(int(os.environ["ERROR_CHANNEL_ID"]))
    await channel.send(f"Erreur: " + msg)
`

**Comment by ccrvlh** [comment]
You can take a look at #1697 and #1405 which are related. I haven't looked into this for a while now since I've been mostly working with sync code lately, but I _think_ you have two options: (1) customize your worker to be async and have it's own loop or (2) customize the job to handle async functions. I've ran a couple of experiments with this in the past, and it's something I would like to work on the future, but it will take a while unfortunately.
