### ISSUE TITLE
Worker rq:worker:... found an unhandled exception, quitting (ModuleNotFoundError: No module named 'resource')

### ISSUE THREAD

**Issue by ssikiki** [rq/rq#2014]
LOG:
2023-12-07 14:34:39,991 INFO    [rq.worker:ForkPoolWorker-1:31045] host.10.24.25.33: consumer.grpc_client.vm_act('set_br', body={'attach': True, 'mac': ...}) (4f8f521e-095d-4551-9909-45ff0aec3049)
2023-12-07 14:34:46,624 INFO    [rq.worker:ForkPoolWorker-1:27587] host.10.24.25.33: Job OK (4f8f521e-095d-4551-9909-45ff0aec3049)
2023-12-07 14:34:46,624 INFO    [rq.worker:ForkPoolWorker-1:27587] Result is kept for 86400 seconds
2023-12-07 14:34:46,628 ERROR   [rq.worker:ForkPoolWorker-1:31045] Worker rq:worker:86d3d3c8d8114ea6b56bb9ee4fe28c21: found an unhandled exception, quitting...
Traceback (most recent call last):
File "rq/worker.py", line 432, in work
File "rq/worker.py", line 1273, in execute_job
File "rq/worker.py", line 1210, in monitor_work_horse
File "rq/worker.py", line 951, in wait_for_horse
ModuleNotFoundError: No module named 'resource'
2023-12-07 14:34:46,630 INFO    [rq.worker:ForkPoolWorker-1:31045] Unsubscribing from channel rq:pubsub:86d3d3c8d8114ea6b56bb9ee4fe28c21

ENV:
OS: Centos7.6
PY：3.6.8
RQ: 1.15.1

Hello，I found such a problem. rq worker no longer accepts new tasks. How should I deal with it?

**Comment by ssikiki** [comment]
1. 4f8f521e-095d-4551-9909-45ff0aec3049 task is Job OK
2. I can't reproduce this problem, it seems to happen randomly.
3. If this problem occurs, it can only be restored by restarting the worker.

**Comment by selwin** [comment]
What Python version are you running the workers on?

**Comment by ssikiki** [comment]
python 3.6.8

**Comment by ssikiki** [comment]
> What Python version are you running the workers on?

3.6.8

**Comment by selwin** [comment]
Try upgrading your Python to 3.7. We no longer support Python 3.6.

**Comment by ssikiki** [comment]
rq/worker.py  wait_for_horse
```python
        ...
        with contextlib.suppress(ChildProcessError):  # ChildProcessError: [Errno 10] No child processes
            pid, stat, rusage = os.wait4(self.horse_pid, 0)
        ...
```
changed to
```python
        ...
        with contextlib.suppress(ChildProcessError):  # ChildProcessError: [Errno 10] No child processes
            try:
                pid, stat, rusage = os.wait4(self.horse_pid, 0)
            except Exception as e:
                pid, stat = os.waitpid(self.horse_pid, 0)
        ...
```
It works both on CentOS7 and Ubuntu20+
