### ISSUE TITLE
ValueError: Invalid attribute name for job callback

### ISSUE THREAD

**Issue by krlx** [rq/rq#2035]
```
AttributeError: module '**scheduler.triggers**' has no attribute ''

During handling of the above exception, another exception occurred:
Traceback (most recent call last):  
File "/venv/lib/python3.11/site-packages/rq/worker.py", line 1449, in perform_job    job.execute_failure_callback(self.death_penalty_class, *exc_info)  
File "/venv/lib/python3.11/site-packages/rq/job.py", line 1423, in execute_failure_callback    if not self.failure_callback:            
File "/venv/lib/python3.11/site-packages/rq/job.py", line 448, in failure_callback    self._failure_callback = import_attribute(self._failure_callback_name)                           
File "/venv/lib/python3.11/site-packages/rq/utils.py", line 120, in import_attribute    
raise ValueError('Invalid attribute name: %s' % attribute_name)
ValueError: Invalid attribute name: **report_failure**'
```

I'm using the command `rqscheduler`. The command is executed from a location that can import `report_failure` from `scheduler.triggers`.

Versions:
```
django_rq-2.10.1
rq-1.15.1
rq_scheduler-0.13.1
```

**Comment by krlx** [comment]
Note: This seems to happen randomly. Sometimes it works, some minutes later for the next scheduled job, I'm seeing this error

**Comment by stelmath** [comment]
Same here

**Comment by hexkey** [comment]
same issue, without django, on flask. Unable to import function to run as job with same error

```
rq-worker      |   File "/usr/local/lib/python3.12/site-packages/rq/utils.py", line 109, in import_attribute
rq-worker      |     raise ValueError('Invalid attribute name: %s' % name)
```

**Comment by hexkey** [comment]
it seems that this solves the issue but it's not mentioned as requirement, **worker instance** has to have app location added to PYTHONPATH ie:

```export PYTHONPATH="$PYTHONPATH:/app/code"```

or in case of docker:

```ENV PYTHONPATH="$PYTHONPATH:/app/code"```

**Comment by timsaya** [comment]
Having just faced this issue myself, but solutions like @Moby Duck's didn't work, I was able to narrow it down to a circular import error (rq doesn't report the error as a circular import error, but just the blanket AttributeError or something of the like).

If you suspect a circular import, or if @Moby Duck's style solution does not work, try:

open a terminal in the working directory
launch the python from the terminal (i.e., just python or python3 in the terminal prompt)
try to import the function from python running in the terminal (there, you should see an ImportError warning about a possible circular import, if you do indeed have a circular import)


from
[](https://stackoverflow.com/questions/38079222/rq-worker-throwing-valueerror)


it's work for me.

**Comment by rajatasusual** [comment]
@thomasqjohns  you are a legend. This saved me so much time! what a poor unhandled scenario this one is.
