### ISSUE TITLE
keys of command in MULTI calls must be in same slot

### ISSUE THREAD

**Issue by TracyRAN1** [rq/rq#2050]
`16:48:46 Starting worker pool d0b2361c95b04df99f453342b6b6817b with pid 75627...
16:48:46 Starting worker started with PID 75640
16:48:46 Starting worker started with PID 75641
16:48:46 Worker rq:worker:ea1d295198dc4668ba1aaca2138239a5 started with PID 75640, version 1.15.1
16:48:46 Subscribing to channel rq:pubsub:ea1d295198dc4668ba1aaca2138239a5
16:48:46 Worker rq:worker:51c8a43f600746f68f3adde8d784e79b started with PID 75641, version 1.15.1
16:48:46 Subscribing to channel rq:pubsub:51c8a43f600746f68f3adde8d784e79b
16:48:46 *** Listening on rq...
16:48:46 *** Listening on rq...
16:48:55 rq: apps.sms.tasks.send_work_message(UUID('2d3d5419-7f40-4ac7-a96e-659b893dfdc7'), OrderedDict([('ori_chn', 'LH'), ('ori_sys', 'lhtest'), ('ori_seq', 'test000..., {'ori_sys': 'lhtest', 'create_time': '2024-01-10T06:01:08.334900', 'update_...) (513a1850-bc5b-4ed4-9df5-e7991bb93c6d)
16:48:55 [Job 513a1850-bc5b-4ed4-9df5-e7991bb93c6d]: exception raised while executing (apps.sms.tasks.send_work_message)
Traceback (most recent call last):
  File "/xinshi-app/venv/lib/python3.10/site-packages/rq/worker.py", line 1440, in perform_job
    self.handle_job_success(job=job, queue=queue, started_job_registry=started_job_registry)
  File "/xinshi-app/venv/lib/python3.10/site-packages/rq/worker.py", line 1399, in handle_job_success
    pipeline.execute()
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1478, in execute
    return conn.retry.call_with_retry(
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1479, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1348, in _execute_transaction
    response = self.parse_response(connection, "_")
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 1416, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/client.py", line 553, in parse_response
    response = connection.read_response()
  File "/xinshi-app/venv/lib/python3.10/site-packages/redis/connection.py", line 524, in read_response
    raise response
redis.exceptions.ResponseError: keys of command in MULTI calls must be in same slot`

**Comment by selwin** [comment]
I've never seen this error before. Are you by any chance using Redis cluster?

**Comment by TracyRAN1** [comment]
Yes, in our production environment at the company, I am required to use Redis cluster.

**Comment by TracyRAN1** [comment]
Within a Django environment, I'm utilizing RQ (Redis Queue) for message push tasks where the messages are being successfully delivered. Nonetheless, an issue surfaces during the process of updating the job status.
I think changing the cache key prefix from rq:xxxx to {rq}:xxxx might solve the problem, as it would guarantee that keys land in the same slot.
I attempted to modify the source code myself, but unfortunately, I was unsuccessful, which brings me here seeking assistance. @selwin

**Comment by lee-jian-hui** [comment]
hi there i encoutnered the exact similar issue as you except i encountered the CROSSLOT error. I am also required to use redis cluster in prod.

a quick fix i have tested and works is overwriting the keys using hash tag concept in redis to make sure the keys in multi-key operations are in the same hash slot.

Again, this is a temporary fix, until someone eventually pushes a PR to provide support for redis cluster operations. Or a simple config for devs to specify the key prefix they would want for all keys in rq.

`from rq import Queue

Queue.redis_queue_namespace_prefix = 'rq:{workers}:queue:'
Queue.redis_queues_keys = 'rq:{workers}:queues'

from rq import suspension
suspension.WORKERS_SUSPENDED = 'rq:{workers}:suspended'

from rq import worker_registration
worker_registration.WORKERS_BY_QUEUE_KEY = 'rq:{workers}:%s'
worker_registration.REDIS_WORKER_KEYS = 'rq:{workers}'

from rq import worker
worker.WORKER_QUEUES_KEY = 'rq:{workers}:%s:queues'
`

**Comment by nikita698** [comment]
I face the same issue, I'm required to use a redis cluster in production so I'm quite stuck.
If there's any workaround I'd be happy to know.

**Comment by selwin** [comment]
> EDIT: my bad, it looks like you need to overwrite all keys and append the prefix to apply the hashtag to the keys being used in rq. This is a very stupid method but it works. It does defeat the purpose of redis cluster.

Does adding another prefix in front of “rq” work @lee-jian-hui ? For example using f'prefix:rq:queues' instead of f'rq:{HASHTAG_PREFIX}:queues'.

if this works, adding a “prefix” capability to RQ may help.

**Comment by lee-jian-hui** [comment]
@selwin apparently it doesnt work reliably, this hack is considerably unreliable and i would advise against the effort involved.

adding the prefix helps to ensure all the slots hash to the same node, but I think this defeats the purpose of enterprise redis anyway.

I have also encountered some state management concerning rq where some of the redis keys are not properly overwritten by me, e.g. rq:executions:{id} and this did not seem to appear in the framework code, im not sure if you can advise which part of the code does this as well.
