### ISSUE TITLE
Worker fails on job success

### ISSUE THREAD

**Issue by Gaddsky** [rq/rq#2149]
Python 3.12.7
rq==2.0.0
redis==4.6.0

Job performed without any issue, but worker fail with the following taceback:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/rq/worker.py", line 1583, in perform_job
    self.handle_job_success(job=job, queue=queue, started_job_registry=started_job_registry)
  File "/usr/local/lib/python3.12/site-packages/rq/worker.py", line 1518, in handle_job_success
    self.increment_total_working_time(job.ended_at - job.started_at, pipeline)  # type: ignore
                                      ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
```

In Python 3.12 `datetime.datetime.utcnow()` become [deprecated](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow), `datetime.datetime.now(datetime.UTC)` should be used instead. Looks like one of `end_date` or `start_date` somehow lost timezone data.

Temporary workaround in user code:
```python
from rq import Worker

class PatchedWorker(Worker):
    def handle_job_success(self, job: Job, queue: Queue, started_job_registry: StartedJobRegistry):
        if job.ended_at and job.started_at:
            if job.ended_at.tzinfo is None:
                job.ended_at = job.ended_at.replace(tzinfo=UTC)
            if job.started_at.tzinfo is None:
                job.started_at = job.started_at.replace(tzinfo=UTC)
        super().handle_job_success(job, queue, started_job_registry)

worker = PatchedWorker(queues)
```

**Comment by Harrolee** [comment]
For the same reason, the worker also fails on `handle_job_failure`. I tried replacing all occurrences of `datetime.datetime.utcnow()` with `datetime.UTC`. Somehow, `job.ended_at` still loses its timezone info.

I'll see what I can figure out.

**Comment by Harrolee** [comment]
TZ info is getting lost in the Retry process.

**Comment by argilya** [comment]
Experiencing the same problem with

```
// python libraries
rq==2.0.0
redis==5.2.1
django-rq=3.0.0

// docker images
Python 3.11.11
Redis 7.2
```

**Comment by selwin** [comment]
Hi guys, are you able to provide a snippet of code to reproduce this error? We have a test for handling success and failure callbacks and they're passing just fine. 

https://github.com/rq/rq/blob/dd95a761a9906c684076ab76c66cc78a07405dee/tests/test_callbacks.py#L142

**Comment by rcstanciu** [comment]
Fixed by #2180

**Comment by Gaddsky** [comment]
Thank you all, especially @deathtracktor. Now it works!
