### ISSUE TITLE
worker crashes and does not start due to: `NoSuchGroupError`

### ISSUE THREAD

**Issue by malud** [rq/rq#2158]
Hi,

For some reason (crash?), I had two group members in `rq:groups`, but only one of them exists as the key `rq:group:6748951b2157c4cf993530a3`. This results in a `NoSuchGroupError `exception.

Is there any process that should trigger such a cleanup? Currently, this issue is causing worker reboots/backoff without proper handling.

## Traceback
```
vscode ➜ /workspace $ rq worker
09:01:21 Worker rq:worker:c770a7f0ec2c49b4a0acd078fac43137 started with PID 9574, version 2.0.0
09:01:21 Subscribing to channel rq:pubsub:c770a7f0ec2c49b4a0acd078fac43137
09:01:21 *** Listening on default...
09:01:21 Cleaning registries for queue: default
09:01:21 Worker rq:worker:c770a7f0ec2c49b4a0acd078fac43137: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/rq/worker.py", line 570, in work
    self.run_maintenance_tasks()
  File "/home/vscode/.local/lib/python3.12/site-packages/rq/worker.py", line 951, in run_maintenance_tasks
    Group.clean_registries(connection=self.connection)
  File "/home/vscode/.local/lib/python3.12/site-packages/rq/group.py", line 103, in clean_registries
    groups = Group.all(connection=connection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/rq/group.py", line 92, in all
    return [cls.fetch(key, connection=connection) for key in group_keys]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/rq/group.py", line 85, in fetch
    raise NoSuchGroupError
rq.exceptions.NoSuchGroupError
09:01:21 Unsubscribing from channel rq:pubsub:c770a7f0ec2c49b4a0acd078fac43137
```

## Reason / Redis

```
127.0.0.1:6379[1]> keys rq:group*
1) "rq:group:6748951b2157c4cf993530a3"
2) "rq:groups"
127.0.0.1:6379[1]> SMEMBERS rq:groups
1) "6735e0a9c45a795d05123618"
2) "6748951b2157c4cf993530a3"
```

My current workaround is a custom worker file which runs `clean_up_groups` before calling `worker.work()`

```python
...
from rq.group import Group
from rq.worker import Worker

redis_conn = Redis()
async def clean_up_groups():
    groups = redis_conn.smembers(Group.REDIS_GROUP_KEY)
    for group in groups:
        group_name = Group.REDIS_GROUP_NAME_PREFIX + str(group)
        exist = redis_conn.exists(group_name)
        if not exist:
            print("removing stale group", group_name)
            redis_conn.srem(Group.REDIS_GROUP_KEY, group)


asyncio.run(clean_up_groups())

w = Worker([...], connection=redis_conn)
w.work()
```

**Comment by selwin** [comment]
This is fixed in https://github.com/rq/rq/pull/2150 and 2.1.0 is up on PyPI.
