### ISSUE TITLE
Website example is no-go

### ISSUE THREAD

**Issue by 1xch** [rq/rq#235]
from http://python-rq.org/docs/

Put this into command line python:

```
import requests

def count_words_at_url(url):
    resp = requests.get(url)
    return len(resp.text.split())

from rq import Connection, Queue
from redis import Redis
redis_conn = Redis()
q = Queue(connection=redis_conn)
job = q.enqueue(count_words_at_url, 'http://nvie.com')
```

results in:

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/zv/.virtualenvs/j/local/lib/python2.7/site-packages/rq/queue.py", line 159, in enqueue
'Functions from the __main__ module cannot be processed '
>>> ValueError: Functions from the __main__ module cannot be processed by workers.
```

ok....

so try:

```
job = q.enqueue('count_words_at_url', 'http://nvie.com')
```

and get:

```
21:31:27 default: count_words_at_url('http://nvie.com') (76d9a75b-0479-4927-afb2-9f9af5964697)
21:31:27 ValueError: need more than 1 value to unpack
Traceback (most recent call last):
File "/home/zv/.virtualenvs/j/local/lib/python2.7/site-packages/rq/worker.py", line 410, in perform_job
rv = job.perform()
File "/home/zv/.virtualenvs/j/local/lib/python2.7/site-packages/rq/job.py", line 344, in perform
self._result = self.func(*self.args, **self.kwargs)
File "/home/zv/.virtualenvs/j/local/lib/python2.7/site-packages/rq/job.py", line 131, in func
module_name, func_name = func_name.rsplit('.', 1)
ValueError: need more than 1 value to unpack

21:31:27 Moving job to failed queue.
21:31:27
21:31:27 *** Listening on default...
```

**Comment by pavel-odintsov** [comment]
Nice suggestion. There are no information about it on site :(

**Comment by a2htray** [comment]
using `str` works.
