### ISSUE TITLE
TypeError: can't pickle PyCapsule objects

### ISSUE THREAD

**Issue by xnaveira** [rq/rq#283]
Hi, I'm trying to incorporate rq to a django project. It seems to work but I get the following on the worker output:

```
20:41:30 TypeError: can't pickle PyCapsule objects
Traceback (most recent call last):
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 422, in perform_job
    job.save(pipeline=pipeline)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/job.py", line 313, in save
    obj['result'] = dumps(self._result)
  File "/home/neptune/env_django/venv/lib64/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle PyCapsule objects

20:41:30 Moving job to failed queue.
Traceback (most recent call last):
  File "/home/neptune/env_django/venv/bin/rqworker", line 9, in <module>
    load_entry_point('rq==0.3.11', 'console_scripts', 'rqworker')()
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/scripts/rqworker.py", line 90, in main
    w.work(burst=args.burst)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 330, in work
    self.fork_and_perform_job(job)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 360, in fork_and_perform_job
    self.main_work_horse(job)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 395, in main_work_horse
    success = self.perform_job(job)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 429, in perform_job
    self.handle_exception(job, *sys.exc_info())
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 456, in handle_exception
    fallthrough = handler(job, *exc_info)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/worker.py", line 470, in move_to_failed_queue
    self.failed_queue.quarantine(job, exc_info=exc_string)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/queue.py", line 333, in quarantine
    return self.enqueue_job(job, timeout=job.timeout, set_meta_data=False)
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/queue.py", line 198, in enqueue_job
    job.save()
  File "/home/neptune/env_django/venv/lib/python2.7/site-packages/rq/job.py", line 313, in save
    obj['result'] = dumps(self._result)
  File "/home/neptune/env_django/venv/lib64/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle PyCapsule objects
```

There is no reference to my code so I was wondering if you have any idea of what's going on? As mentioned, the enqueued function is actually doing its job...

Thank you.

**Comment by dontsovcmc** [comment]
This error can be if source code changes:

1. you have you own class MyResult
2. you call function with MyResult return
3. you change source code and delete MyResult class
4. you fetch job from queue: Exception: can't pickle MyResult... because there is no MyResult in the code.
