### ISSUE TITLE
weave.inline error: CompileError: error: Input/output error

### ISSUE THREAD

**Issue by jmetz** [rq/rq#317]
When attempting to run a function that uses weave.inline I get a `CompileError`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 411, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 348, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File ".../testing/redis/redis_weave.py", line 22, in test_func
    inline('std::cout << a << "\\n" << b << std::endl; c=a+b;std::cout<<c<<std::endl;',['a', 'b','c'])
  File "/usr/local/lib/python2.7/dist-packages/scipy/weave/inline_tools.py", line 361, in inline
    **kw)
  File "/usr/local/lib/python2.7/dist-packages/scipy/weave/inline_tools.py", line 491, in compile_function
    verbose=verbose, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scipy/weave/ext_tools.py", line 373, in compile
    verbose=verbose, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scipy/weave/build_tools.py", line 279, in build_extension
    setup(name=module_name, ext_modules=[ext],verbose=verb)
  File "/usr/local/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.7/distutils/core.py", line 162, in setup
    raise SystemExit, error
CompileError: error: Input/output error
```

If I run the function without rq (which causes weave to compile and cache the c-code) it then runs fine, so the issue is when trying to compile within a rq job.perform call. 
Any pointers would be much appreciated!

The minimal example is: 

```
def test_func():
    a = 100
    b = 200
    c = 747
    inline('std::cout << a << "\\n" << b << std::endl; c=a+b;std::cout<<c<<std::endl;',['a'  , 'b','c'])
    return c

if __name__ == '__main__':
    q = Queue('test', connection=Redis())
    job = q.enqueue_call(
          func        = test_func,
          args        =  (),
          kwargs    = {}
          )
```

**Comment by lowercase00** [comment]
Related to Python 2.7. Closing,
