### ISSUE TITLE
UnicodeEncodeError of rqinfo

### ISSUE THREAD

**Issue by who-you-me** [rq/rq#352]
I encountered error below when running rqinfo.

```
Traceback (most recent call last):
  File "/usr/local/bin/rqinfo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rq/scripts/rqinfo.py", line 192, in main
    interval(args.interval, func, args)
  File "/usr/local/lib/python2.7/dist-packages/rq/scripts/rqinfo.py", line 159, in interval
    func(args)
  File "/usr/local/lib/python2.7/dist-packages/rq/scripts/rqinfo.py", line 131, in show_both
    show_queues(args)
  File "/usr/local/lib/python2.7/dist-packages/rq/scripts/rqinfo.py", line 73, in show_queues
    print(line)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2588' in position 19: ordinal not in range(256)
```

And I found non-ascii character in line 69 of rqinfo.py.

```
            chart = green('|' + '■' * int(ratio * count))
```

Why don't you set appropriate encoding or use ascii character (for example, use "-" instead of "■") ?

**Comment by john2x** [comment]
Running into this issue with version 0.4.6 on Ubuntu 14.04
