### ISSUE TITLE
ResponseError unknown command 'EVALSHA'

### ISSUE THREAD

**Issue by abessifi** [rq/rq#398]
I run RQ tests from master branch (should be stable) on Debian :
Distro : Debian 7.4
Python Redis Lib : 2.10.1 (installed with pip)
redis-server : 2.4.14 (default package on the Debian repo).

However, I got 2 failed tests with the same exception "ResponseError: unknown command 'EVALSHA"
I think it is because of the Redis version (2.4.14 not implementing EVALSHA). If it is the root reason, I'll try to fix it.

This is the exception traceback :

ERROR: test_empty_queue (test_queue.TestQueue)
Emptying queues.
Traceback (most recent call last):
  File "/root/redis-queue/rq/tests/test_queue.py", line 49, in test_empty_queue
    q.empty()
  File "rq/queue.py", line 96, in empty
    return script(keys=[self.key])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2594, in **call**
    return client.evalsha(self.sha, len(keys), _args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1855, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 529, in execute_command
    return self.parse_response(connection, command_name, *_options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 541, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 550, in read_response
    raise response
ResponseError: unknown command 'EVALSHA'

ERROR: test_empty_removes_jobs (test_queue.TestQueue)
Emptying a queue deletes the associated job objects
Traceback (most recent call last):
  File "/root/redis-queue/rq/tests/test_queue.py", line 59, in test_empty_removes_jobs
    q.empty()
  File "rq/queue.py", line 96, in empty
    return script(keys=[self.key])
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2594, in **call**
    return client.evalsha(self.sha, len(keys), _args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1855, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 529, in execute_command
    return self.parse_response(connection, command_name, *_options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 541, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 550, in read_response
    raise response
ResponseError: unknown command 'EVALSHA'

**Comment by Deepakchawla** [comment]
I am getting some error and below result of `pip freeze` command

asgi-redis==1.4.3
asgiref==1.1.2
attrs==17.2.0
autobahn==17.9.2
Automat==0.6.0
channels==1.1.8
constantly==15.1.0
daphne==1.3.0
Django==1.8.14
hyperlink==17.3.1
incremental==17.5.0
msgpack-python==0.4.8
olefile==0.44
Pillow==4.2.1
pypiwin32==219
pytz==2017.2
redis==2.10.6
six==1.11.0
SQLAlchemy==1.1.14
Twisted==17.5.0
txaio==2.8.2
zope.interface==4.4.2
