### ISSUE TITLE
QUESTION: rq in WSL (windows substystem for linux)?

### ISSUE THREAD

**Issue by copernico** [rq/rq#937]
According to the docs, rq cannot be run in Windows.

I suspect it should be runnable in Linux under the Windows Subsystem for Linux (WSL).

I tested it runnig redis in docker (in windows) and the ```./run_tests``` script and (after manually installing a bunch of required packages), I obtained the following, which looks encouraging if one only looks at the fact that of 210 tests, only 5 failed. 

 Can anyone help me understand if those failures are critical? I have the impression that they all fail just because of some issue creating temp files in ```/tmp```

```
======================================================================
ERROR: test_worker_pid (test_cli.TestRQCli)
rq worker -u <url> /tmp/..
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/i064196/rq/tests/test_cli.py", line 168, in test_worker_pid
    pid = self.tmpdir.join('rq.pid')
AttributeError: 'TestRQCli' object has no attribute 'tmpdir'

======================================================================
ERROR: test_run_access_self (test_worker.TestWorkerSubprocess)
Schedule a job, then run the worker as subprocess
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/i064196/rq/tests/test_worker.py", line 921, in test_run_access_self
    subprocess.check_call(['rqworker', '-u', self.redis_url, '-b'])
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'rqworker'

======================================================================
ERROR: test_run_empty_queue (test_worker.TestWorkerSubprocess)
Run the worker in its own process with an empty queue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/i064196/rq/tests/test_worker.py", line 915, in test_run_empty_queue
    subprocess.check_call(['rqworker', '-u', self.redis_url, '-b'])
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'rqworker'

======================================================================
ERROR: test_run_scheduled_access_self (test_worker.TestWorkerSubprocess)
Schedule a job that schedules a job, then run the worker as subprocess
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/i064196/rq/tests/test_worker.py", line 930, in test_run_scheduled_access_self
    subprocess.check_call(['rqworker', '-u', self.redis_url, '-b'])
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'rqworker'

======================================================================
FAIL: test_handle_shutdown_request (test_worker.HerokuWorkerShutdownTestCase)
Mutate HerokuWorker so _horse_pid refers to an artificial process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/i064196/rq/tests/test_worker.py", line 1017, in test_handle_shutdown_request
    self.assertEqual(p.exitcode, -34)
AssertionError: None != -34

----------------------------------------------------------------------
Ran 210 tests in 28.685s

FAILED (failures=1, errors=4)
```

**Comment by samuelcolvin** [comment]
I'm not that sure how WSL works, but [the documentation](https://docs.python.org/3/library/multiprocessing.html) for python multiprocessing points to numerous differences in behaviour on windows. Those differences intern are due to fundamental differences in how windows handles processes and the termination of processes.

I suspect those failures (especially `test_handle_shutdown_request`) point to rq relying on multiprocessing behaviour which is fundamentally different on windows and linux.

**Comment by samuelcolvin** [comment]
Have you tried running rq with wsl? If so does it all run normally?

I would try terminating rq, both with a job running and without and with a long job running that doesn't finish before the hard shutdown. 

If that all works we could perhaps fix or skip those tests.

**Comment by copernico** [comment]
Yes, the example provided with the rq source code worked perfectly, as far as I can tell.
See screenshot below.

<img width="1266" alt="rq" src="https://user-images.githubusercontent.com/2268970/37256266-69a280f2-2558-11e8-84f3-f32f0de4587c.PNG">

**Comment by samuelcolvin** [comment]
Including hot shutdown?

Well then I guess it works. What do you want us to do next?

**Comment by copernico** [comment]
Yes, single CTRL+C and double CTRL+C work as expected, I suppose.
