### ISSUE TITLE
redis cluster mode not support multi-key support

### ISSUE THREAD

**Issue by adolphlwq** [rq/rq#940]
Hi, I hack django-rq to support redis cluster, my code is https://github.com/adolphlwq/django-rq/commit/03d1fcb1e96c7603ced5e6a307a42d909e53d10d, which I use [redis-py-cluster](https://github.com/Grokzen/redis-py-cluster).
But I run into error:`rediscluster.exceptions.ClusterCrossSlotError: Keys in request don't hash to the same slot`. The traceback is:
```shell
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django_rq/management/commands/rqworker.py", line 100, in handle
    w.work(burst=options.get('burst', False))
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 488, in work
    result = self.dequeue_job_and_maintain_ttl(timeout)
  File "/usr/local/lib/python3.5/site-packages/rq/worker.py", line 521, in dequeue_job_and_maintain_ttl
    job_class=self.job_class)
  File "/usr/local/lib/python3.5/site-packages/rq/queue.py", line 454, in dequeue_any
    result = cls.lpop(queue_keys, timeout, connection=connection)
  File "/usr/local/lib/python3.5/site-packages/rq/queue.py", line 404, in lpop
    result = connection.blpop(queue_keys, timeout)
  File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/usr/local/lib/python3.5/site-packages/rediscluster/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/rediscluster/client.py", line 357, in execute_command
    return self.parse_response(r, command, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
rediscluster.exceptions.ClusterCrossSlotError: Keys in request don't hash to the same slot
```

It seems `connection.blpop()` not support in redis cluster mode. **So will you support this feature?** related issue is https://github.com/rq/django-rq/issues/280. Thanks.
```shell
File "/usr/local/lib/python3.5/site-packages/rq/queue.py", line 404, in lpop
result = connection.blpop(queue_keys, timeout)
```

**Comment by sjh431** [comment]
It seems that the issue you mentioned has been resolved in version 4.9.5.
https://github.com/redis/ioredis/issues/850
