### ISSUE TITLE
UnicodeEncodeError when using rqinfo with password

### ISSUE THREAD

**Issue by jcounts** [rq/rq#952]
I get the following traceback:
```
Traceback (most recent call last):
  File "/opt/sapi/gearbox/venv_0.1.107/bin/rqinfo", line 11, in <module>
    sys.exit(main())
  File "/opt/sapi/gearbox/venv_0.1.107/lib/python2.7/site-packages/rq/scripts/rqinfo.py", line 192, in main
    interval(args.interval, func, args)
  File "/opt/sapi/gearbox/venv_0.1.107/lib/python2.7/site-packages/rq/scripts/rqinfo.py", line 159, in interval
    func(args)
  File "/opt/sapi/gearbox/venv_0.1.107/lib/python2.7/site-packages/rq/scripts/rqinfo.py", line 131, in show_both
    show_queues(args)
  File "/opt/sapi/gearbox/venv_0.1.107/lib/python2.7/site-packages/rq/scripts/rqinfo.py", line 73, in show_queues
    print(line)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 19-33: ordinal not in range(256)
```
when running `rqinfo` with the password option.

**Comment by selwin** [comment]
Did you pass in your password via the cli's `--url` argument?

**Comment by selwin** [comment]
`rqinfo --url redis://user:pass@127.0.0.1/` should work.
