### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode

### ISSUE THREAD

**Issue by Ablex** [rq/rq#980]
Everything worked perfectly. Including utf-8. 
But at some point, errors began to appear when the worker started up. A similar error occurs on different computers. Now the workers does not start at all. 
In the queue of failed, this error does not fall. The number of jobs in the Normal queue does not change.
Restarting the redis server does not help.
Because of what it can be? Or what do I need to do to fix it?
Thank you!

python 2.7.15
RQ version 0.12.0
Redis server v=4.0.9

The traceback is:

> RQ worker u'rq:worker:5c7857186cff.82' started, version 0.12.0
08:57:08 *** Listening on Normal, default...
08:57:08 Cleaning registries for queue: Normal
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 11, in <module>
    load_entry_point('rq', 'console_scripts', 'rq')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/src/rq/rq/cli/cli.py", line 75, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/src/rq/rq/cli/cli.py", line 236, in worker
    worker.work(burst=burst, logging_level=logging_level)
  File "/src/rq/rq/worker.py", line 478, in work
    self.clean_registries()
  File "/src/rq/rq/worker.py", line 892, in clean_registries
    clean_registries(queue)
  File "/src/rq/rq/registry.py", line 156, in clean_registries
    registry.cleanup()
  File "/src/rq/rq/registry.py", line 104, in cleanup
    job.save(pipeline=pipeline, include_meta=False)
  File "/src/rq/rq/job.py", line 516, in save
    connection.hmset(key, self.to_dict(include_meta=include_meta))
  File "/src/rq/rq/job.py", line 487, in to_dict
    obj['exc_info'] = zlib.compress(str(self.exc_info).encode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 734-739: ordinal not in range(128)

**Comment by selwin** [comment]
It looks like `job.exc_info` contains unicode characters and that causes this line https://github.com/rq/rq/blob/master/rq/job.py#L487 to fail.

Could you please open a PR to fix this?

**Comment by Ablex** [comment]
apparently, the problem was in redis.
I reinstalled the database, and the problem disappeared.

Bad method of course, but it was necessary to do something urgently.
