### ISSUE TITLE
not work well with Chinese exec info

### ISSUE THREAD

**Issue by chaosconst** [rq/rq#996]
当我们运行的程序的错误堆栈的日志里面有中文的提示的时候，似乎程序会出现崩溃的问题。
When the log of the error stack of the program we run contains a Chinese hint, it seems that the program will crash.

下面的小修改可能可以解决这个问题，至少对我来说有效：
The following minor changes may solve this problem, at least for me:

yuandeMacBook-Pro:src yuan$ diff /Library/Python/2.7/site-packages/rq/job.py /tmp/job.py 
487c487
<             obj['exc_info'] = zlib.compress(str(self.exc_info.encode('utf-8')))
---
>             obj['exc_info'] = zlib.compress(str(self.exc_info).encode('utf-8'))

下面是错误日志：
Here's the error log:

INFO:root:skills_core.skill_1394f9cfc48e23c2e9f543f0ac990b1f loaded.
00:50:25 ValueError: Extra data: line 1 column 12 - line 1 column 23 (char 11 - 22)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_0c2f9c352995f05a04c9da3cb8551b55.py", line 10, in run_skill
    run_intention("从它构造对象")
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_1394f9cfc48e23c2e9f543f0ac990b1f.py", line 8, in run_skill
    return json.loads(p[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 12 - line 1 column 23 (char 11 - 22)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_0c2f9c352995f05a04c9da3cb8551b55.py", line 10, in run_skill
    run_intention("从它构造对象")
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_1394f9cfc48e23c2e9f543f0ac990b1f.py", line 8, in run_skill
    return json.loads(p[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 12 - line 1 column 23 (char 11 - 22)
ERROR:rq.worker:ValueError: Extra data: line 1 column 12 - line 1 column 23 (char 11 - 22)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_0c2f9c352995f05a04c9da3cb8551b55.py", line 10, in run_skill
    run_intention("从它构造对象")
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_1394f9cfc48e23c2e9f543f0ac990b1f.py", line 8, in run_skill
    return json.loads(p[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 12 - line 1 column 23 (char 11 - 22)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/Library/Python/2.7/site-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_0c2f9c352995f05a04c9da3cb8551b55.py", line 10, in run_skill
    run_intention("从它构造对象")
  File "./core_func.py", line 58, in run_intention
    res = skill_now.run_skill(p_list, context)
  File "./skills_core/skill_1394f9cfc48e23c2e9f543f0ac990b1f.py", line 8, in run_skill
    return json.loads(p[0])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 12 - line 1 column 23 (char 11 - 22)
00:50:25 Moving job to u'failed' queue
WARNING:rq.worker:Moving job to u'failed' queue
Traceback (most recent call last):
  File "/usr/local/bin/rq", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rq/cli/cli.py", line 75, in wrapper
    return ctx.invoke(func, cli_config, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rq/cli/cli.py", line 236, in worker
    worker.work(burst=burst, logging_level=logging_level)
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 493, in work
    self.execute_job(job, queue)
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 662, in execute_job
    self.fork_work_horse(job, queue)
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 599, in fork_work_horse
    self.main_work_horse(job, queue)
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 677, in main_work_horse
    success = self.perform_job(job, queue)
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 808, in perform_job
    self.handle_exception(job, *sys.exc_info())
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 844, in handle_exception
    fallthrough = handler(job, *exc_info)
  File "/Library/Python/2.7/site-packages/rq/worker.py", line 858, in move_to_failed_queue
    move_to_failed_queue(job, *exc_info)
  File "/Library/Python/2.7/site-packages/rq/handlers.py", line 12, in move_to_failed_queue
    failed_queue.quarantine(job, exc_info=exc_string)
  File "/Library/Python/2.7/site-packages/rq/queue.py", line 520, in quarantine
    job.save(pipeline=pipeline, include_meta=False)
  File "/Library/Python/2.7/site-packages/rq/job.py", line 516, in save
    connection.hmset(key, self.to_dict(include_meta=include_meta))
  File "/Library/Python/2.7/site-packages/rq/job.py", line 487, in to_dict
    obj['exc_info'] = zlib.compress(str(self.exc_info).encode('utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 579-584: ordinal not in range(128)

**Comment by selwin** [comment]
Do you mind opening a PR for this?

**Comment by chaosconst** [comment]
I opened a pull request at https://github.com/rq/rq/pull/1000
